name: goldchain-roughnet

services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db
    container_name: goldchain-roughnet-redis-db

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db
    container_name: goldchain-roughnet-db

  backend:
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    container_name: goldchain-roughnet-backend
    image: ${GOLDCHAIN_BACKEND_IMAGE}
    pull_policy: never
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        DISABLE_WEBAPP: "true"
        ADMIN_PANEL_ENABLED: "false"
        API_V1_READ_METHODS_DISABLED: "false"
        API_V1_WRITE_METHODS_DISABLED: "false"
        RELEASE_VERSION: ${GOLDCHAIN_RELEASE_VERSION}
    links:
      - db:database
    environment:
      DISABLE_WEBAPP: "true"
      ETHEREUM_JSONRPC_HTTP_URL: ${GOLDCHAIN_RPC_HTTP_URL}
      ETHEREUM_JSONRPC_TRACE_URL: ${GOLDCHAIN_RPC_TRACE_URL}
      ETHEREUM_JSONRPC_WS_URL: ${GOLDCHAIN_RPC_WS_URL}
      CHAIN_ID: ${GOLDCHAIN_CHAIN_ID}
      NETWORK: ${GOLDCHAIN_NETWORK}
      SUBNETWORK: ${GOLDCHAIN_SUBNETWORK}
      COIN: ${GOLDCHAIN_COIN}
      COIN_NAME: ${GOLDCHAIN_COIN_NAME}
      LOGO_TEXT: ${GOLDCHAIN_LOGO_TEXT}
      GOLDSCAN_HOST: ${GOLDCHAIN_GOLDSCAN_HOST}
      GOLDSCAN_PROTOCOL: ${GOLDCHAIN_GOLDSCAN_PROTOCOL}
      WEBAPP_URL: ${GOLDCHAIN_WEBAPP_URL}
      API_URL: ${GOLDCHAIN_API_URL}
      JSON_RPC: ${GOLDCHAIN_JSON_RPC}
      SHOW_TESTNET_LABEL: ${GOLDCHAIN_SHOW_TESTNET_LABEL}
      TESTNET_LABEL_TEXT: ${GOLDCHAIN_TESTNET_LABEL_TEXT}
      MICROSERVICE_SIG_PROVIDER_ENABLED: "false"
      MICROSERVICE_VISUALIZE_SOL2UML_ENABLED: "false"
      NFT_MEDIA_HANDLER_ENABLED: "false"
      NFT_MEDIA_HANDLER_REMOTE_DISPATCHER_NODE_MODE_ENABLED: "false"

  frontend:
    depends_on:
      - backend
    container_name: goldchain-roughnet-frontend
    restart: always
    platform: linux/amd64
    image: ${GOLDCHAIN_FRONTEND_IMAGE}
    pull_policy: never
    build:
      context: ../../goldscan-frontend
      dockerfile: ./Dockerfile
    env_file:
      - ./goldchain-roughnet.frontend.env
    environment:
      NEXT_PUBLIC_STATS_API_HOST: ""
      NEXT_PUBLIC_VISUALIZE_API_HOST: ""

  proxy:
    depends_on:
      - backend
      - frontend
    extends:
      file: ./services/nginx-explorer.yml
      service: proxy
    container_name: goldchain-roughnet-proxy
    volumes:
      - "./proxy/explorer.conf.template:/etc/nginx/templates/default.conf.template"
    environment:
      BACK_PROXY_PASS: http://backend:4000
      FRONT_PROXY_PASS: http://frontend:3000
