name: gilttestnet_deb_profiles

on:
  push:
    paths:
      - '**'
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'

jobs:
  build:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      # Variables
      - name: Adding TAG to ENV
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - name: adding version
        run: |
          NUMERIC_VERSION=$( echo ${{ env.GIT_TAG }} | sed 's/[^0-9.]//g' ) 
          echo "VERSION=$NUMERIC_VERSION" >> $GITHUB_ENV

      - name: Making directory structure for yaml
        run: mkdir -p packaging/deb/gilt/var/lib/gilt
      - name: making directory structure for the systemd
        run: mkdir -p packaging/deb/gilt/lib/systemd/system
      - name: Delete control file
        run: rm -rf packaging/deb/gilt/DEBIAN/control

      # Control file creation
      - name: create control file
        run: |
          touch packaging/deb/gilt/DEBIAN/control
          echo "Package: gilt-profile" >> packaging/deb/gilt/DEBIAN/control
          echo "Version: ${{ env.VERSION }}" >> packaging/deb/gilt/DEBIAN/control
          echo "Section: base" >> packaging/deb/gilt/DEBIAN/control
          echo "Priority: optional" >> packaging/deb/gilt/DEBIAN/control
          echo "Architecture: all" >> packaging/deb/gilt/DEBIAN/control
          echo "Maintainer: devops@gilt.technology" >> packaging/deb/gilt/DEBIAN/control
          echo "Description: gilt profile package" >> packaging/deb/gilt/DEBIAN/control

      # Bootnode Profile
      - name: Prepping ${{ env.NETWORK }} ${{ env.NODE }} bootnode for ${{ env.ARCH }}
        run: cp -rp  packaging/deb/gilt packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: all
          NODE: bootnode
          NETWORK: gilttestnet
      - name: Putting toml for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/testnet-gilttestnet/sentry/sentry/gilt/config.toml packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/var/lib/gilt/
        env:
          ARCH: all
          NODE: bootnode
          NETWORK: gilttestnet
      - name: Copying the preinst for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/preinst packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/preinst
        env:
          ARCH: all
          NODE: bootnode
          NETWORK: gilttestnet
      - name: Copying the postinst for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/postinst.profile packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/postinst
        env:
          ARCH: all
          NODE: bootnode
          NETWORK: gilttestnet
      - name: Copying the prerm for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/prerm packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/prerm
        env:
          ARCH: all
          NODE: bootnode
          NETWORK: gilttestnet
      - name: Copying the postrm for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/postrm packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/postrm
        env:
          ARCH: all
          NODE: bootnode
          NETWORK: gilttestnet
      - name: Copying systemd file for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/systemd/gilt_bootnode.service packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/lib/systemd/system/gilt.service
        env:
          ARCH: all
          NODE: bootnode
          NETWORK: gilttestnet

      - name: Running package build for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: dpkg-deb --build --root-owner-group packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: all
          NODE: bootnode
          NETWORK: gilttestnet

      # Sentry Profile
      - name: Prepping ${{ env.NETWORK }} ${{ env.NODE }} node for ${{ env.ARCH }}
        run: cp -rp  packaging/deb/gilt packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: all
          NODE: sentry
          NETWORK: gilttestnet
      - name: Putting toml for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/testnet-gilttestnet/sentry/sentry/gilt/config.toml packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/var/lib/gilt/
        env:
          ARCH: all
          NODE: sentry
          NETWORK: gilttestnet
      - name: Copying the preinst for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/preinst packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/preinst
        env:
          ARCH: all
          NODE: sentry
          NETWORK: gilttestnet
      - name: Copying the postinst for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/postinst.profile packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/postinst
        env:
          ARCH: all
          NODE: sentry
          NETWORK: gilttestnet
      - name: Copying the prerm for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/prerm packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/prerm
        env:
          ARCH: all
          NODE: sentry
          NETWORK: gilttestnet
      - name: Copying the postrm for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/postrm packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/postrm
        env:
          ARCH: all
          NODE: sentry
          NETWORK: gilttestnet
      - name: Copying systemd file for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/systemd/gilt.service packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/lib/systemd/system/
        env:
          ARCH: all
          NODE: sentry
          NETWORK: gilttestnet

      - name: Running package build for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: dpkg-deb --build --root-owner-group packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: all
          NODE: sentry
          NETWORK: gilttestnet

      # PBSS Sentry
      - name: Prepping ${{ env.NETWORK }} ${{ env.NODE }} node for ${{ env.ARCH }}
        run: cp -rp  packaging/deb/gilt packaging/deb/gilt-pbss-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: all
          NODE: sentry
          NETWORK: gilttestnet
      - name: Putting toml for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/testnet-gilttestnet/sentry/sentry/gilt/pbss_config.toml packaging/deb/gilt-pbss-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/var/lib/gilt/config.toml
        env:
          ARCH: all
          NODE: sentry
          NETWORK: gilttestnet
      - name: Copying the preinst for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/preinst packaging/deb/gilt-pbss-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/preinst
        env:
          ARCH: all
          NODE: sentry
          NETWORK: gilttestnet
      - name: Copying the postinst for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/postinst.profile packaging/deb/gilt-pbss-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/postinst
        env:
          ARCH: all
          NODE: sentry
          NETWORK: gilttestnet
      - name: Copying the prerm for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/prerm packaging/deb/gilt-pbss-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/prerm
        env:
          ARCH: all
          NODE: sentry
          NETWORK: gilttestnet
      - name: Copying the postrm for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/postrm packaging/deb/gilt-pbss-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/postrm
        env:
          ARCH: all
          NODE: sentry
          NETWORK: gilttestnet
      - name: Copying systemd file for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/systemd/gilt.service packaging/deb/gilt-pbss-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/lib/systemd/system/
        env:
          ARCH: all
          NODE: sentry
          NETWORK: gilttestnet
      - name: Running package build for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: dpkg-deb --build --root-owner-group packaging/deb/gilt-pbss-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: all
          NODE: sentry
          NETWORK: gilttestnet

      # Validator Profile
      - name: Prepping Gilt ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/deb/gilt packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: all
          NODE: validator
          NETWORK: gilttestnet
      - name: Copying Postinstall script for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/postinst.profile packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/postinst
        env:
          ARCH: all
          NODE: validator
          NETWORK: gilttestnet
      - name: Copying Prerm script for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/prerm packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/prerm
        env:
          ARCH: all
          NODE: validator
          NETWORK: gilttestnet
      - name: Copying Postrm script for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/postrm packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/postrm
        env:
          ARCH: all
          NODE: validator
          NETWORK: gilttestnet
      - name: Copying config.toml for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/testnet-gilttestnet/sentry/validator/gilt/config.toml packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/var/lib/gilt/
        env:
          ARCH: all
          NODE: validator
          NETWORK: gilttestnet
      - name: Copying systemd file for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/systemd/gilt.service packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/lib/systemd/system/
        env:
          ARCH: all
          NODE: validator
          NETWORK: gilttestnet
      - name: Building gilt ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }} profile
        run: dpkg-deb --build --root-owner-group packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: all
          NODE: validator
          NETWORK: gilttestnet

      # PBSS Validator
      - name: Prepping Gilt ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/deb/gilt packaging/deb/gilt-pbss-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: all
          NODE: validator
          NETWORK: gilttestnet
      - name: Copying Postinstall script for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/postinst.profile packaging/deb/gilt-pbss-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/postinst
        env:
          ARCH: all
          NODE: validator
          NETWORK: gilttestnet
      - name: Copying Prerm script for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/prerm packaging/deb/gilt-pbss-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/prerm
        env:
          ARCH: all
          NODE: validator
          NETWORK: gilttestnet
      - name: Copying Postrm script for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/postrm packaging/deb/gilt-pbss-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/postrm
        env:
          ARCH: all
          NODE: validator
          NETWORK: gilttestnet
      - name: Copying config.toml for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/testnet-gilttestnet/sentry/validator/gilt/pbss_config.toml packaging/deb/gilt-pbss-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/var/lib/gilt/config.toml
        env:
          ARCH: all
          NODE: validator
          NETWORK: gilttestnet
      - name: Copying systemd file for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/systemd/gilt.service packaging/deb/gilt-pbss-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/lib/systemd/system/
        env:
          ARCH: all
          NODE: validator
          NETWORK: gilttestnet
      - name: Building gilt ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }} profile
        run: dpkg-deb --build --root-owner-group packaging/deb/gilt-pbss-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: all
          NODE: validator
          NETWORK: gilttestnet

      # Archive Profile
      - name: Creating gilt ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/deb/gilt packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: all
          NODE: archive
          NETWORK: gilttestnet
      - name: Copying profile preinst file for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/preinst packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/preinst
        env:
          ARCH: all
          NODE: archive
          NETWORK: gilttestnet
      - name: Copying the profile postinst for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/postinst.profile packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/postinst
        env:
          ARCH: all
          NODE: archive
          NETWORK: gilttestnet
      - name: Copying profile prerm file for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/prerm packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/prerm
        env:
          ARCH: all
          NODE: archive
          NETWORK: gilttestnet
      - name: Copying profile postrm file for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/postrm packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/postrm
        env:
          ARCH: all
          NODE: archive
          NETWORK: gilttestnet
      - name: Copying the toml for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/testnet-gilttestnet/archive/config.toml packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/var/lib/gilt/
        env:
          ARCH: all
          NODE: archive
          NETWORK: gilttestnet
      - name: Copying systemd file for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/systemd/gilt.service packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/lib/systemd/system/
        env:
          ARCH: all
          NODE: archive
          NETWORK: gilttestnet
      - name: Building gilt ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }} profile
        run: dpkg-deb --build --root-owner-group packaging/deb/gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: all
          NODE: archive
          NETWORK: gilttestnet

      # Shasum
      - name: shasum the gilt debian package
        run: cd packaging/deb/ && sha256sum gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}.deb > gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}.deb.checksum
        env:
          ARCH: all
          NODE: bootnode
          NETWORK: gilttestnet
      - name: shasum the gilt debian package
        run: cd packaging/deb/ && sha256sum gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}.deb > gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}.deb.checksum
        env:
          ARCH: all
          NODE: sentry
          NETWORK: gilttestnet
      - name: shasum the gilt pbss debian package
        run: cd packaging/deb/ && sha256sum gilt-pbss-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}.deb > gilt-pbss-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}.deb.checksum
        env:
          ARCH: all
          NODE: sentry
          NETWORK: gilttestnet
      - name: shasum the gilt-${{ env.ARCH }} debian package
        run: cd packaging/deb/ && sha256sum gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}.deb > gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}.deb.checksum
        env:
          ARCH: all
          NODE: validator
          NETWORK: gilttestnet
      - name: shasum the gilt pbss debian package
        run: cd packaging/deb/ && sha256sum gilt-pbss-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}.deb > gilt-pbss-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}.deb.checksum
        env:
          ARCH: all
          NODE: validator
          NETWORK: gilttestnet
      - name: shasum the gilt debian package
        run: cd packaging/deb/ && sha256sum gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}.deb > gilt-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}.deb.checksum
        env:
          ARCH: all
          NODE: archive
          NETWORK: gilttestnet

      ############ Check and Upload ##########################
      - name: Confirming package built
        run: ls -ltr packaging/deb/ | grep gilt

      - name: Release gilt Packages
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.GIT_TAG }}
          make_latest: false
          files: |
            packaging/deb/gilt-gilttestnet-**.deb
            packaging/deb/gilt-pbss-gilttestnet-**.deb 
            packaging/deb/gilt-gilttestnet-**.deb.checksum
            packaging/deb/gilt-pbss-gilttestnet-**.deb.checksum
            builder/files/genesis-gilttestnet.json
