export enum WalletIds {
  Injected = 'injected',
  Metamask = 'metamask',
  Trust = 'trust',
  Okx = 'okx',
  BinanceW3W = 'BinanceW3W',
  Coinbase = 'coinbase',
  Walletconnect = 'walletconnect',
  Opera = 'opera',
  Brave = 'brave',
  Rabby = 'rabby',
  Math = 'math',
  Tokenpocket = 'tokenpocket',
  Safepal = 'safepal',
  Coin98 = 'coin98',
  Blocto = 'blocto',
  Cyberwallet = 'cyberwallet',
  Petra = 'petra',
  Martian = 'martian',
  Pontem = 'pontem',
  Fewcha = 'fewcha',
  TrustWallet = 'trustWallet',
  SafePal = 'safePal',
  Phantom = 'phantom',
  BitGet = 'bitget',
  Rise = 'rise',
  Msafe = 'msafe',
}
