FROM alpine:3.23

ARG GILT_DIR=/var/lib/gilt-exec/
ENV GILT_DIR=$GILT_DIR

RUN apk add --no-cache ca-certificates && mkdir -p ${GILT_DIR}

WORKDIR ${GILT_DIR}
COPY gilt /usr/bin/
COPY builder/files/genesis-gilttestnet.json ${GILT_DIR}
COPY builder/files/genesis-mainnet-v1.json ${GILT_DIR}
COPY builder/files/genesis-testnet-v4.json ${GILT_DIR}

EXPOSE 8545 8546 8547 30303 30303/udp

ENTRYPOINT ["gilt"]
