// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package chainmanager

import (
	_ "cosmossdk.io/api/amino"
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_ChainParams                         protoreflect.MessageDescriptor
	fd_ChainParams_bor_chain_id            protoreflect.FieldDescriptor
	fd_ChainParams_heimdall_chain_id       protoreflect.FieldDescriptor
	fd_ChainParams_pol_token_address       protoreflect.FieldDescriptor
	fd_ChainParams_staking_manager_address protoreflect.FieldDescriptor
	fd_ChainParams_slash_manager_address   protoreflect.FieldDescriptor
	fd_ChainParams_root_chain_address      protoreflect.FieldDescriptor
	fd_ChainParams_staking_info_address    protoreflect.FieldDescriptor
	fd_ChainParams_state_sender_address    protoreflect.FieldDescriptor
	fd_ChainParams_state_receiver_address  protoreflect.FieldDescriptor
	fd_ChainParams_validator_set_address   protoreflect.FieldDescriptor
)

func init() {
	file_heimdallv2_chainmanager_chainmanager_proto_init()
	md_ChainParams = File_heimdallv2_chainmanager_chainmanager_proto.Messages().ByName("ChainParams")
	fd_ChainParams_bor_chain_id = md_ChainParams.Fields().ByName("bor_chain_id")
	fd_ChainParams_heimdall_chain_id = md_ChainParams.Fields().ByName("heimdall_chain_id")
	fd_ChainParams_pol_token_address = md_ChainParams.Fields().ByName("pol_token_address")
	fd_ChainParams_staking_manager_address = md_ChainParams.Fields().ByName("staking_manager_address")
	fd_ChainParams_slash_manager_address = md_ChainParams.Fields().ByName("slash_manager_address")
	fd_ChainParams_root_chain_address = md_ChainParams.Fields().ByName("root_chain_address")
	fd_ChainParams_staking_info_address = md_ChainParams.Fields().ByName("staking_info_address")
	fd_ChainParams_state_sender_address = md_ChainParams.Fields().ByName("state_sender_address")
	fd_ChainParams_state_receiver_address = md_ChainParams.Fields().ByName("state_receiver_address")
	fd_ChainParams_validator_set_address = md_ChainParams.Fields().ByName("validator_set_address")
}

var _ protoreflect.Message = (*fastReflection_ChainParams)(nil)

type fastReflection_ChainParams ChainParams

func (x *ChainParams) ProtoReflect() protoreflect.Message {
	return (*fastReflection_ChainParams)(x)
}

func (x *ChainParams) slowProtoReflect() protoreflect.Message {
	mi := &file_heimdallv2_chainmanager_chainmanager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_ChainParams_messageType fastReflection_ChainParams_messageType
var _ protoreflect.MessageType = fastReflection_ChainParams_messageType{}

type fastReflection_ChainParams_messageType struct{}

func (x fastReflection_ChainParams_messageType) Zero() protoreflect.Message {
	return (*fastReflection_ChainParams)(nil)
}
func (x fastReflection_ChainParams_messageType) New() protoreflect.Message {
	return new(fastReflection_ChainParams)
}
func (x fastReflection_ChainParams_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_ChainParams
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_ChainParams) Descriptor() protoreflect.MessageDescriptor {
	return md_ChainParams
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_ChainParams) Type() protoreflect.MessageType {
	return _fastReflection_ChainParams_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_ChainParams) New() protoreflect.Message {
	return new(fastReflection_ChainParams)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_ChainParams) Interface() protoreflect.ProtoMessage {
	return (*ChainParams)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_ChainParams) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.BorChainId != "" {
		value := protoreflect.ValueOfString(x.BorChainId)
		if !f(fd_ChainParams_bor_chain_id, value) {
			return
		}
	}
	if x.HeimdallChainId != "" {
		value := protoreflect.ValueOfString(x.HeimdallChainId)
		if !f(fd_ChainParams_heimdall_chain_id, value) {
			return
		}
	}
	if x.PolTokenAddress != "" {
		value := protoreflect.ValueOfString(x.PolTokenAddress)
		if !f(fd_ChainParams_pol_token_address, value) {
			return
		}
	}
	if x.StakingManagerAddress != "" {
		value := protoreflect.ValueOfString(x.StakingManagerAddress)
		if !f(fd_ChainParams_staking_manager_address, value) {
			return
		}
	}
	if x.SlashManagerAddress != "" {
		value := protoreflect.ValueOfString(x.SlashManagerAddress)
		if !f(fd_ChainParams_slash_manager_address, value) {
			return
		}
	}
	if x.RootChainAddress != "" {
		value := protoreflect.ValueOfString(x.RootChainAddress)
		if !f(fd_ChainParams_root_chain_address, value) {
			return
		}
	}
	if x.StakingInfoAddress != "" {
		value := protoreflect.ValueOfString(x.StakingInfoAddress)
		if !f(fd_ChainParams_staking_info_address, value) {
			return
		}
	}
	if x.StateSenderAddress != "" {
		value := protoreflect.ValueOfString(x.StateSenderAddress)
		if !f(fd_ChainParams_state_sender_address, value) {
			return
		}
	}
	if x.StateReceiverAddress != "" {
		value := protoreflect.ValueOfString(x.StateReceiverAddress)
		if !f(fd_ChainParams_state_receiver_address, value) {
			return
		}
	}
	if x.ValidatorSetAddress != "" {
		value := protoreflect.ValueOfString(x.ValidatorSetAddress)
		if !f(fd_ChainParams_validator_set_address, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_ChainParams) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "heimdallv2.chainmanager.ChainParams.bor_chain_id":
		return x.BorChainId != ""
	case "heimdallv2.chainmanager.ChainParams.heimdall_chain_id":
		return x.HeimdallChainId != ""
	case "heimdallv2.chainmanager.ChainParams.pol_token_address":
		return x.PolTokenAddress != ""
	case "heimdallv2.chainmanager.ChainParams.staking_manager_address":
		return x.StakingManagerAddress != ""
	case "heimdallv2.chainmanager.ChainParams.slash_manager_address":
		return x.SlashManagerAddress != ""
	case "heimdallv2.chainmanager.ChainParams.root_chain_address":
		return x.RootChainAddress != ""
	case "heimdallv2.chainmanager.ChainParams.staking_info_address":
		return x.StakingInfoAddress != ""
	case "heimdallv2.chainmanager.ChainParams.state_sender_address":
		return x.StateSenderAddress != ""
	case "heimdallv2.chainmanager.ChainParams.state_receiver_address":
		return x.StateReceiverAddress != ""
	case "heimdallv2.chainmanager.ChainParams.validator_set_address":
		return x.ValidatorSetAddress != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: heimdallv2.chainmanager.ChainParams"))
		}
		panic(fmt.Errorf("message heimdallv2.chainmanager.ChainParams does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ChainParams) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "heimdallv2.chainmanager.ChainParams.bor_chain_id":
		x.BorChainId = ""
	case "heimdallv2.chainmanager.ChainParams.heimdall_chain_id":
		x.HeimdallChainId = ""
	case "heimdallv2.chainmanager.ChainParams.pol_token_address":
		x.PolTokenAddress = ""
	case "heimdallv2.chainmanager.ChainParams.staking_manager_address":
		x.StakingManagerAddress = ""
	case "heimdallv2.chainmanager.ChainParams.slash_manager_address":
		x.SlashManagerAddress = ""
	case "heimdallv2.chainmanager.ChainParams.root_chain_address":
		x.RootChainAddress = ""
	case "heimdallv2.chainmanager.ChainParams.staking_info_address":
		x.StakingInfoAddress = ""
	case "heimdallv2.chainmanager.ChainParams.state_sender_address":
		x.StateSenderAddress = ""
	case "heimdallv2.chainmanager.ChainParams.state_receiver_address":
		x.StateReceiverAddress = ""
	case "heimdallv2.chainmanager.ChainParams.validator_set_address":
		x.ValidatorSetAddress = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: heimdallv2.chainmanager.ChainParams"))
		}
		panic(fmt.Errorf("message heimdallv2.chainmanager.ChainParams does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_ChainParams) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "heimdallv2.chainmanager.ChainParams.bor_chain_id":
		value := x.BorChainId
		return protoreflect.ValueOfString(value)
	case "heimdallv2.chainmanager.ChainParams.heimdall_chain_id":
		value := x.HeimdallChainId
		return protoreflect.ValueOfString(value)
	case "heimdallv2.chainmanager.ChainParams.pol_token_address":
		value := x.PolTokenAddress
		return protoreflect.ValueOfString(value)
	case "heimdallv2.chainmanager.ChainParams.staking_manager_address":
		value := x.StakingManagerAddress
		return protoreflect.ValueOfString(value)
	case "heimdallv2.chainmanager.ChainParams.slash_manager_address":
		value := x.SlashManagerAddress
		return protoreflect.ValueOfString(value)
	case "heimdallv2.chainmanager.ChainParams.root_chain_address":
		value := x.RootChainAddress
		return protoreflect.ValueOfString(value)
	case "heimdallv2.chainmanager.ChainParams.staking_info_address":
		value := x.StakingInfoAddress
		return protoreflect.ValueOfString(value)
	case "heimdallv2.chainmanager.ChainParams.state_sender_address":
		value := x.StateSenderAddress
		return protoreflect.ValueOfString(value)
	case "heimdallv2.chainmanager.ChainParams.state_receiver_address":
		value := x.StateReceiverAddress
		return protoreflect.ValueOfString(value)
	case "heimdallv2.chainmanager.ChainParams.validator_set_address":
		value := x.ValidatorSetAddress
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: heimdallv2.chainmanager.ChainParams"))
		}
		panic(fmt.Errorf("message heimdallv2.chainmanager.ChainParams does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ChainParams) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "heimdallv2.chainmanager.ChainParams.bor_chain_id":
		x.BorChainId = value.Interface().(string)
	case "heimdallv2.chainmanager.ChainParams.heimdall_chain_id":
		x.HeimdallChainId = value.Interface().(string)
	case "heimdallv2.chainmanager.ChainParams.pol_token_address":
		x.PolTokenAddress = value.Interface().(string)
	case "heimdallv2.chainmanager.ChainParams.staking_manager_address":
		x.StakingManagerAddress = value.Interface().(string)
	case "heimdallv2.chainmanager.ChainParams.slash_manager_address":
		x.SlashManagerAddress = value.Interface().(string)
	case "heimdallv2.chainmanager.ChainParams.root_chain_address":
		x.RootChainAddress = value.Interface().(string)
	case "heimdallv2.chainmanager.ChainParams.staking_info_address":
		x.StakingInfoAddress = value.Interface().(string)
	case "heimdallv2.chainmanager.ChainParams.state_sender_address":
		x.StateSenderAddress = value.Interface().(string)
	case "heimdallv2.chainmanager.ChainParams.state_receiver_address":
		x.StateReceiverAddress = value.Interface().(string)
	case "heimdallv2.chainmanager.ChainParams.validator_set_address":
		x.ValidatorSetAddress = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: heimdallv2.chainmanager.ChainParams"))
		}
		panic(fmt.Errorf("message heimdallv2.chainmanager.ChainParams does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ChainParams) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "heimdallv2.chainmanager.ChainParams.bor_chain_id":
		panic(fmt.Errorf("field bor_chain_id of message heimdallv2.chainmanager.ChainParams is not mutable"))
	case "heimdallv2.chainmanager.ChainParams.heimdall_chain_id":
		panic(fmt.Errorf("field heimdall_chain_id of message heimdallv2.chainmanager.ChainParams is not mutable"))
	case "heimdallv2.chainmanager.ChainParams.pol_token_address":
		panic(fmt.Errorf("field pol_token_address of message heimdallv2.chainmanager.ChainParams is not mutable"))
	case "heimdallv2.chainmanager.ChainParams.staking_manager_address":
		panic(fmt.Errorf("field staking_manager_address of message heimdallv2.chainmanager.ChainParams is not mutable"))
	case "heimdallv2.chainmanager.ChainParams.slash_manager_address":
		panic(fmt.Errorf("field slash_manager_address of message heimdallv2.chainmanager.ChainParams is not mutable"))
	case "heimdallv2.chainmanager.ChainParams.root_chain_address":
		panic(fmt.Errorf("field root_chain_address of message heimdallv2.chainmanager.ChainParams is not mutable"))
	case "heimdallv2.chainmanager.ChainParams.staking_info_address":
		panic(fmt.Errorf("field staking_info_address of message heimdallv2.chainmanager.ChainParams is not mutable"))
	case "heimdallv2.chainmanager.ChainParams.state_sender_address":
		panic(fmt.Errorf("field state_sender_address of message heimdallv2.chainmanager.ChainParams is not mutable"))
	case "heimdallv2.chainmanager.ChainParams.state_receiver_address":
		panic(fmt.Errorf("field state_receiver_address of message heimdallv2.chainmanager.ChainParams is not mutable"))
	case "heimdallv2.chainmanager.ChainParams.validator_set_address":
		panic(fmt.Errorf("field validator_set_address of message heimdallv2.chainmanager.ChainParams is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: heimdallv2.chainmanager.ChainParams"))
		}
		panic(fmt.Errorf("message heimdallv2.chainmanager.ChainParams does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_ChainParams) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "heimdallv2.chainmanager.ChainParams.bor_chain_id":
		return protoreflect.ValueOfString("")
	case "heimdallv2.chainmanager.ChainParams.heimdall_chain_id":
		return protoreflect.ValueOfString("")
	case "heimdallv2.chainmanager.ChainParams.pol_token_address":
		return protoreflect.ValueOfString("")
	case "heimdallv2.chainmanager.ChainParams.staking_manager_address":
		return protoreflect.ValueOfString("")
	case "heimdallv2.chainmanager.ChainParams.slash_manager_address":
		return protoreflect.ValueOfString("")
	case "heimdallv2.chainmanager.ChainParams.root_chain_address":
		return protoreflect.ValueOfString("")
	case "heimdallv2.chainmanager.ChainParams.staking_info_address":
		return protoreflect.ValueOfString("")
	case "heimdallv2.chainmanager.ChainParams.state_sender_address":
		return protoreflect.ValueOfString("")
	case "heimdallv2.chainmanager.ChainParams.state_receiver_address":
		return protoreflect.ValueOfString("")
	case "heimdallv2.chainmanager.ChainParams.validator_set_address":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: heimdallv2.chainmanager.ChainParams"))
		}
		panic(fmt.Errorf("message heimdallv2.chainmanager.ChainParams does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_ChainParams) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in heimdallv2.chainmanager.ChainParams", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_ChainParams) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_ChainParams) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_ChainParams) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_ChainParams) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*ChainParams)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.BorChainId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.HeimdallChainId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.PolTokenAddress)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.StakingManagerAddress)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.SlashManagerAddress)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.RootChainAddress)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.StakingInfoAddress)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.StateSenderAddress)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.StateReceiverAddress)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.ValidatorSetAddress)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*ChainParams)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.ValidatorSetAddress) > 0 {
			i -= len(x.ValidatorSetAddress)
			copy(dAtA[i:], x.ValidatorSetAddress)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ValidatorSetAddress)))
			i--
			dAtA[i] = 0x52
		}
		if len(x.StateReceiverAddress) > 0 {
			i -= len(x.StateReceiverAddress)
			copy(dAtA[i:], x.StateReceiverAddress)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.StateReceiverAddress)))
			i--
			dAtA[i] = 0x4a
		}
		if len(x.StateSenderAddress) > 0 {
			i -= len(x.StateSenderAddress)
			copy(dAtA[i:], x.StateSenderAddress)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.StateSenderAddress)))
			i--
			dAtA[i] = 0x42
		}
		if len(x.StakingInfoAddress) > 0 {
			i -= len(x.StakingInfoAddress)
			copy(dAtA[i:], x.StakingInfoAddress)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.StakingInfoAddress)))
			i--
			dAtA[i] = 0x3a
		}
		if len(x.RootChainAddress) > 0 {
			i -= len(x.RootChainAddress)
			copy(dAtA[i:], x.RootChainAddress)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.RootChainAddress)))
			i--
			dAtA[i] = 0x32
		}
		if len(x.SlashManagerAddress) > 0 {
			i -= len(x.SlashManagerAddress)
			copy(dAtA[i:], x.SlashManagerAddress)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.SlashManagerAddress)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.StakingManagerAddress) > 0 {
			i -= len(x.StakingManagerAddress)
			copy(dAtA[i:], x.StakingManagerAddress)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.StakingManagerAddress)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.PolTokenAddress) > 0 {
			i -= len(x.PolTokenAddress)
			copy(dAtA[i:], x.PolTokenAddress)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.PolTokenAddress)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.HeimdallChainId) > 0 {
			i -= len(x.HeimdallChainId)
			copy(dAtA[i:], x.HeimdallChainId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.HeimdallChainId)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.BorChainId) > 0 {
			i -= len(x.BorChainId)
			copy(dAtA[i:], x.BorChainId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.BorChainId)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*ChainParams)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: ChainParams: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: ChainParams: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field BorChainId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.BorChainId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field HeimdallChainId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.HeimdallChainId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PolTokenAddress", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.PolTokenAddress = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field StakingManagerAddress", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.StakingManagerAddress = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SlashManagerAddress", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.SlashManagerAddress = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field RootChainAddress", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.RootChainAddress = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field StakingInfoAddress", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.StakingInfoAddress = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 8:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field StateSenderAddress", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.StateSenderAddress = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 9:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field StateReceiverAddress", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.StateReceiverAddress = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 10:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ValidatorSetAddress", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ValidatorSetAddress = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_Params                             protoreflect.MessageDescriptor
	fd_Params_chain_params                protoreflect.FieldDescriptor
	fd_Params_main_chain_tx_confirmations protoreflect.FieldDescriptor
	fd_Params_bor_chain_tx_confirmations  protoreflect.FieldDescriptor
)

func init() {
	file_heimdallv2_chainmanager_chainmanager_proto_init()
	md_Params = File_heimdallv2_chainmanager_chainmanager_proto.Messages().ByName("Params")
	fd_Params_chain_params = md_Params.Fields().ByName("chain_params")
	fd_Params_main_chain_tx_confirmations = md_Params.Fields().ByName("main_chain_tx_confirmations")
	fd_Params_bor_chain_tx_confirmations = md_Params.Fields().ByName("bor_chain_tx_confirmations")
}

var _ protoreflect.Message = (*fastReflection_Params)(nil)

type fastReflection_Params Params

func (x *Params) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Params)(x)
}

func (x *Params) slowProtoReflect() protoreflect.Message {
	mi := &file_heimdallv2_chainmanager_chainmanager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Params_messageType fastReflection_Params_messageType
var _ protoreflect.MessageType = fastReflection_Params_messageType{}

type fastReflection_Params_messageType struct{}

func (x fastReflection_Params_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Params)(nil)
}
func (x fastReflection_Params_messageType) New() protoreflect.Message {
	return new(fastReflection_Params)
}
func (x fastReflection_Params_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Params
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Params) Descriptor() protoreflect.MessageDescriptor {
	return md_Params
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Params) Type() protoreflect.MessageType {
	return _fastReflection_Params_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Params) New() protoreflect.Message {
	return new(fastReflection_Params)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Params) Interface() protoreflect.ProtoMessage {
	return (*Params)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Params) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.ChainParams != nil {
		value := protoreflect.ValueOfMessage(x.ChainParams.ProtoReflect())
		if !f(fd_Params_chain_params, value) {
			return
		}
	}
	if x.MainChainTxConfirmations != uint64(0) {
		value := protoreflect.ValueOfUint64(x.MainChainTxConfirmations)
		if !f(fd_Params_main_chain_tx_confirmations, value) {
			return
		}
	}
	if x.BorChainTxConfirmations != uint64(0) {
		value := protoreflect.ValueOfUint64(x.BorChainTxConfirmations)
		if !f(fd_Params_bor_chain_tx_confirmations, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Params) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "heimdallv2.chainmanager.Params.chain_params":
		return x.ChainParams != nil
	case "heimdallv2.chainmanager.Params.main_chain_tx_confirmations":
		return x.MainChainTxConfirmations != uint64(0)
	case "heimdallv2.chainmanager.Params.bor_chain_tx_confirmations":
		return x.BorChainTxConfirmations != uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: heimdallv2.chainmanager.Params"))
		}
		panic(fmt.Errorf("message heimdallv2.chainmanager.Params does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Params) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "heimdallv2.chainmanager.Params.chain_params":
		x.ChainParams = nil
	case "heimdallv2.chainmanager.Params.main_chain_tx_confirmations":
		x.MainChainTxConfirmations = uint64(0)
	case "heimdallv2.chainmanager.Params.bor_chain_tx_confirmations":
		x.BorChainTxConfirmations = uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: heimdallv2.chainmanager.Params"))
		}
		panic(fmt.Errorf("message heimdallv2.chainmanager.Params does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Params) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "heimdallv2.chainmanager.Params.chain_params":
		value := x.ChainParams
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "heimdallv2.chainmanager.Params.main_chain_tx_confirmations":
		value := x.MainChainTxConfirmations
		return protoreflect.ValueOfUint64(value)
	case "heimdallv2.chainmanager.Params.bor_chain_tx_confirmations":
		value := x.BorChainTxConfirmations
		return protoreflect.ValueOfUint64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: heimdallv2.chainmanager.Params"))
		}
		panic(fmt.Errorf("message heimdallv2.chainmanager.Params does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Params) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "heimdallv2.chainmanager.Params.chain_params":
		x.ChainParams = value.Message().Interface().(*ChainParams)
	case "heimdallv2.chainmanager.Params.main_chain_tx_confirmations":
		x.MainChainTxConfirmations = value.Uint()
	case "heimdallv2.chainmanager.Params.bor_chain_tx_confirmations":
		x.BorChainTxConfirmations = value.Uint()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: heimdallv2.chainmanager.Params"))
		}
		panic(fmt.Errorf("message heimdallv2.chainmanager.Params does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Params) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "heimdallv2.chainmanager.Params.chain_params":
		if x.ChainParams == nil {
			x.ChainParams = new(ChainParams)
		}
		return protoreflect.ValueOfMessage(x.ChainParams.ProtoReflect())
	case "heimdallv2.chainmanager.Params.main_chain_tx_confirmations":
		panic(fmt.Errorf("field main_chain_tx_confirmations of message heimdallv2.chainmanager.Params is not mutable"))
	case "heimdallv2.chainmanager.Params.bor_chain_tx_confirmations":
		panic(fmt.Errorf("field bor_chain_tx_confirmations of message heimdallv2.chainmanager.Params is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: heimdallv2.chainmanager.Params"))
		}
		panic(fmt.Errorf("message heimdallv2.chainmanager.Params does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Params) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "heimdallv2.chainmanager.Params.chain_params":
		m := new(ChainParams)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "heimdallv2.chainmanager.Params.main_chain_tx_confirmations":
		return protoreflect.ValueOfUint64(uint64(0))
	case "heimdallv2.chainmanager.Params.bor_chain_tx_confirmations":
		return protoreflect.ValueOfUint64(uint64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: heimdallv2.chainmanager.Params"))
		}
		panic(fmt.Errorf("message heimdallv2.chainmanager.Params does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Params) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in heimdallv2.chainmanager.Params", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Params) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Params) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Params) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Params) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Params)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.ChainParams != nil {
			l = options.Size(x.ChainParams)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.MainChainTxConfirmations != 0 {
			n += 1 + runtime.Sov(uint64(x.MainChainTxConfirmations))
		}
		if x.BorChainTxConfirmations != 0 {
			n += 1 + runtime.Sov(uint64(x.BorChainTxConfirmations))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Params)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.BorChainTxConfirmations != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.BorChainTxConfirmations))
			i--
			dAtA[i] = 0x18
		}
		if x.MainChainTxConfirmations != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.MainChainTxConfirmations))
			i--
			dAtA[i] = 0x10
		}
		if x.ChainParams != nil {
			encoded, err := options.Marshal(x.ChainParams)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Params)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Params: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ChainParams", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.ChainParams == nil {
					x.ChainParams = &ChainParams{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.ChainParams); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 2:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MainChainTxConfirmations", wireType)
				}
				x.MainChainTxConfirmations = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.MainChainTxConfirmations |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field BorChainTxConfirmations", wireType)
				}
				x.BorChainTxConfirmations = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.BorChainTxConfirmations |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: heimdallv2/chainmanager/chainmanager.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChainParams contains configuration for both chains and contract addresses.
type ChainParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Chain ID of the Bor (child) chain.
	BorChainId string `protobuf:"bytes,1,opt,name=bor_chain_id,json=borChainId,proto3" json:"bor_chain_id,omitempty"`
	// Chain ID of the Heimdall chain.
	HeimdallChainId string `protobuf:"bytes,2,opt,name=heimdall_chain_id,json=heimdallChainId,proto3" json:"heimdall_chain_id,omitempty"`
	// Address of the POL token contract on the root chain.
	PolTokenAddress string `protobuf:"bytes,3,opt,name=pol_token_address,json=polTokenAddress,proto3" json:"pol_token_address,omitempty"`
	// Address of the staking manager contract on the root chain.
	StakingManagerAddress string `protobuf:"bytes,4,opt,name=staking_manager_address,json=stakingManagerAddress,proto3" json:"staking_manager_address,omitempty"`
	// Address of the slash manager contract on the root chain.
	SlashManagerAddress string `protobuf:"bytes,5,opt,name=slash_manager_address,json=slashManagerAddress,proto3" json:"slash_manager_address,omitempty"`
	// Address of the root chain contract (checkpoint submission).
	RootChainAddress string `protobuf:"bytes,6,opt,name=root_chain_address,json=rootChainAddress,proto3" json:"root_chain_address,omitempty"`
	// Address of the staking info contract on the root chain.
	StakingInfoAddress string `protobuf:"bytes,7,opt,name=staking_info_address,json=stakingInfoAddress,proto3" json:"staking_info_address,omitempty"`
	// Address of the state sender contract on the root chain.
	StateSenderAddress string `protobuf:"bytes,8,opt,name=state_sender_address,json=stateSenderAddress,proto3" json:"state_sender_address,omitempty"`
	// Address of the state receiver contract on the Bor chain.
	StateReceiverAddress string `protobuf:"bytes,9,opt,name=state_receiver_address,json=stateReceiverAddress,proto3" json:"state_receiver_address,omitempty"`
	// Address of the validator set contract on the root chain.
	ValidatorSetAddress string `protobuf:"bytes,10,opt,name=validator_set_address,json=validatorSetAddress,proto3" json:"validator_set_address,omitempty"`
}

func (x *ChainParams) Reset() {
	*x = ChainParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_heimdallv2_chainmanager_chainmanager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChainParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainParams) ProtoMessage() {}

// Deprecated: Use ChainParams.ProtoReflect.Descriptor instead.
func (*ChainParams) Descriptor() ([]byte, []int) {
	return file_heimdallv2_chainmanager_chainmanager_proto_rawDescGZIP(), []int{0}
}

func (x *ChainParams) GetBorChainId() string {
	if x != nil {
		return x.BorChainId
	}
	return ""
}

func (x *ChainParams) GetHeimdallChainId() string {
	if x != nil {
		return x.HeimdallChainId
	}
	return ""
}

func (x *ChainParams) GetPolTokenAddress() string {
	if x != nil {
		return x.PolTokenAddress
	}
	return ""
}

func (x *ChainParams) GetStakingManagerAddress() string {
	if x != nil {
		return x.StakingManagerAddress
	}
	return ""
}

func (x *ChainParams) GetSlashManagerAddress() string {
	if x != nil {
		return x.SlashManagerAddress
	}
	return ""
}

func (x *ChainParams) GetRootChainAddress() string {
	if x != nil {
		return x.RootChainAddress
	}
	return ""
}

func (x *ChainParams) GetStakingInfoAddress() string {
	if x != nil {
		return x.StakingInfoAddress
	}
	return ""
}

func (x *ChainParams) GetStateSenderAddress() string {
	if x != nil {
		return x.StateSenderAddress
	}
	return ""
}

func (x *ChainParams) GetStateReceiverAddress() string {
	if x != nil {
		return x.StateReceiverAddress
	}
	return ""
}

func (x *ChainParams) GetValidatorSetAddress() string {
	if x != nil {
		return x.ValidatorSetAddress
	}
	return ""
}

// Params defines the parameters for the chainmanager module.
type Params struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Chain configuration and contract addresses.
	ChainParams *ChainParams `protobuf:"bytes,1,opt,name=chain_params,json=chainParams,proto3" json:"chain_params,omitempty"`
	// Number of confirmations required for main chain transactions.
	MainChainTxConfirmations uint64 `protobuf:"varint,2,opt,name=main_chain_tx_confirmations,json=mainChainTxConfirmations,proto3" json:"main_chain_tx_confirmations,omitempty"`
	// Number of confirmations required for Bor chain transactions.
	BorChainTxConfirmations uint64 `protobuf:"varint,3,opt,name=bor_chain_tx_confirmations,json=borChainTxConfirmations,proto3" json:"bor_chain_tx_confirmations,omitempty"`
}

func (x *Params) Reset() {
	*x = Params{}
	if protoimpl.UnsafeEnabled {
		mi := &file_heimdallv2_chainmanager_chainmanager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_heimdallv2_chainmanager_chainmanager_proto_rawDescGZIP(), []int{1}
}

func (x *Params) GetChainParams() *ChainParams {
	if x != nil {
		return x.ChainParams
	}
	return nil
}

func (x *Params) GetMainChainTxConfirmations() uint64 {
	if x != nil {
		return x.MainChainTxConfirmations
	}
	return 0
}

func (x *Params) GetBorChainTxConfirmations() uint64 {
	if x != nil {
		return x.BorChainTxConfirmations
	}
	return 0
}

var File_heimdallv2_chainmanager_chainmanager_proto protoreflect.FileDescriptor

var file_heimdallv2_chainmanager_chainmanager_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x68, 0x65, 0x69, 0x6d, 0x64, 0x61, 0x6c, 0x6c, 0x76, 0x32, 0x2f, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x68, 0x65,
	0x69, 0x6d, 0x64, 0x61, 0x6c, 0x6c, 0x76, 0x32, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x61, 0x6d, 0x69,
	0x6e, 0x6f, 0x2f, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbb,
	0x04, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x27,
	0x0a, 0x0c, 0x62, 0x6f, 0x72, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x05, 0xa8, 0xe7, 0xb0, 0x2a, 0x01, 0x52, 0x0a, 0x62, 0x6f, 0x72,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x11, 0x68, 0x65, 0x69, 0x6d, 0x64,
	0x61, 0x6c, 0x6c, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x05, 0xa8, 0xe7, 0xb0, 0x2a, 0x01, 0x52, 0x0f, 0x68, 0x65, 0x69, 0x6d, 0x64,
	0x61, 0x6c, 0x6c, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x11, 0x70, 0x6f,
	0x6c, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x05, 0xa8, 0xe7, 0xb0, 0x2a, 0x01, 0x52, 0x0f, 0x70, 0x6f,
	0x6c, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x3d, 0x0a,
	0x17, 0x73, 0x74, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x05,
	0xa8, 0xe7, 0xb0, 0x2a, 0x01, 0x52, 0x15, 0x73, 0x74, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x39, 0x0a, 0x15,
	0x73, 0x6c, 0x61, 0x73, 0x68, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x42, 0x05, 0xa8, 0xe7, 0xb0,
	0x2a, 0x01, 0x52, 0x13, 0x73, 0x6c, 0x61, 0x73, 0x68, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x33, 0x0a, 0x12, 0x72, 0x6f, 0x6f, 0x74, 0x5f,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x05, 0xa8, 0xe7, 0xb0, 0x2a, 0x01, 0x52, 0x10, 0x72, 0x6f, 0x6f, 0x74,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x37, 0x0a, 0x14,
	0x73, 0x74, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x42, 0x05, 0xa8, 0xe7, 0xb0, 0x2a,
	0x01, 0x52, 0x12, 0x73, 0x74, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x37, 0x0a, 0x14, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x05, 0xa8, 0xe7, 0xb0, 0x2a, 0x01, 0x52, 0x12, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x3b,
	0x0a, 0x16, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x42, 0x05,
	0xa8, 0xe7, 0xb0, 0x2a, 0x01, 0x52, 0x14, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x39, 0x0a, 0x15, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x73, 0x65, 0x74, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x42, 0x05, 0xa8, 0xe7, 0xb0, 0x2a,
	0x01, 0x52, 0x13, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x74, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x3a, 0x04, 0xe8, 0xa0, 0x1f, 0x01, 0x22, 0xec, 0x01, 0x0a,
	0x06, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x52, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x68, 0x65, 0x69, 0x6d, 0x64, 0x61, 0x6c, 0x6c, 0x76, 0x32, 0x2e, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x42, 0x09, 0xc8, 0xde, 0x1f, 0x00, 0xa8, 0xe7, 0xb0, 0x2a, 0x01, 0x52, 0x0b,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x44, 0x0a, 0x1b, 0x6d,
	0x61, 0x69, 0x6e, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x74, 0x78, 0x5f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x42, 0x05, 0xa8, 0xe7, 0xb0, 0x2a, 0x01, 0x52, 0x18, 0x6d, 0x61, 0x69, 0x6e, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x54, 0x78, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x42, 0x0a, 0x1a, 0x62, 0x6f, 0x72, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x74,
	0x78, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x42, 0x05, 0xa8, 0xe7, 0xb0, 0x2a, 0x01, 0x52, 0x17, 0x62, 0x6f,
	0x72, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x78, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x3a, 0x04, 0xe8, 0xa0, 0x1f, 0x01, 0x42, 0xeb, 0x01, 0x0a, 0x1b,
	0x63, 0x6f, 0x6d, 0x2e, 0x68, 0x65, 0x69, 0x6d, 0x64, 0x61, 0x6c, 0x6c, 0x76, 0x32, 0x2e, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x42, 0x11, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x30, 0x78, 0x50,
	0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x2f, 0x68, 0x65, 0x69, 0x6d, 0x64, 0x61, 0x6c, 0x6c, 0x2d,
	0x76, 0x32, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x65, 0x69, 0x6d, 0x64, 0x61, 0x6c, 0x6c, 0x76,
	0x32, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0xa2, 0x02,
	0x03, 0x48, 0x43, 0x58, 0xaa, 0x02, 0x17, 0x48, 0x65, 0x69, 0x6d, 0x64, 0x61, 0x6c, 0x6c, 0x76,
	0x32, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0xca, 0x02,
	0x17, 0x48, 0x65, 0x69, 0x6d, 0x64, 0x61, 0x6c, 0x6c, 0x76, 0x32, 0x5c, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0xe2, 0x02, 0x23, 0x48, 0x65, 0x69, 0x6d, 0x64,
	0x61, 0x6c, 0x6c, 0x76, 0x32, 0x5c, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x18, 0x48, 0x65, 0x69, 0x6d, 0x64, 0x61, 0x6c, 0x6c, 0x76, 0x32, 0x3a, 0x3a, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_heimdallv2_chainmanager_chainmanager_proto_rawDescOnce sync.Once
	file_heimdallv2_chainmanager_chainmanager_proto_rawDescData = file_heimdallv2_chainmanager_chainmanager_proto_rawDesc
)

func file_heimdallv2_chainmanager_chainmanager_proto_rawDescGZIP() []byte {
	file_heimdallv2_chainmanager_chainmanager_proto_rawDescOnce.Do(func() {
		file_heimdallv2_chainmanager_chainmanager_proto_rawDescData = protoimpl.X.CompressGZIP(file_heimdallv2_chainmanager_chainmanager_proto_rawDescData)
	})
	return file_heimdallv2_chainmanager_chainmanager_proto_rawDescData
}

var file_heimdallv2_chainmanager_chainmanager_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_heimdallv2_chainmanager_chainmanager_proto_goTypes = []interface{}{
	(*ChainParams)(nil), // 0: heimdallv2.chainmanager.ChainParams
	(*Params)(nil),      // 1: heimdallv2.chainmanager.Params
}
var file_heimdallv2_chainmanager_chainmanager_proto_depIdxs = []int32{
	0, // 0: heimdallv2.chainmanager.Params.chain_params:type_name -> heimdallv2.chainmanager.ChainParams
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_heimdallv2_chainmanager_chainmanager_proto_init() }
func file_heimdallv2_chainmanager_chainmanager_proto_init() {
	if File_heimdallv2_chainmanager_chainmanager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_heimdallv2_chainmanager_chainmanager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChainParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_heimdallv2_chainmanager_chainmanager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Params); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_heimdallv2_chainmanager_chainmanager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_heimdallv2_chainmanager_chainmanager_proto_goTypes,
		DependencyIndexes: file_heimdallv2_chainmanager_chainmanager_proto_depIdxs,
		MessageInfos:      file_heimdallv2_chainmanager_chainmanager_proto_msgTypes,
	}.Build()
	File_heimdallv2_chainmanager_chainmanager_proto = out.File
	file_heimdallv2_chainmanager_chainmanager_proto_rawDesc = nil
	file_heimdallv2_chainmanager_chainmanager_proto_goTypes = nil
	file_heimdallv2_chainmanager_chainmanager_proto_depIdxs = nil
}
