version: '3.9'

services:
  backend:
    image: ghcr.io/goldscan/${DOCKER_REPO:-goldscan}:${DOCKER_TAG:-latest}
    pull_policy: always
    restart: always
    stop_grace_period: 5m
    container_name: 'backend'
    command: sh -c "bin/goldscan eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/goldscan start"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ../envs/common-goldscan.env
    volumes:
      - ./logs/:/app/logs/
      - ./dets/:/app/dets/
