version: '3.9'

services:
  frontend:
    image: ${GOLDCHAIN_FRONTEND_IMAGE:-goldchain-goldscan-frontend-local:mainnet}
    pull_policy: never
    build:
      context: ../../../goldscan-frontend
      dockerfile: ./Dockerfile
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    env_file:
      -  ../envs/common-frontend.env
      -  ${GOLDCHAIN_FRONTEND_ENV_FILE:-../goldchain-mainnet.frontend.env}
