name: Check documentation ToC
on:
  push:
    branches:
      - v0.38.x
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            docs/architecture/**
            docs/rfc/**
      - run: make check-docs-toc
        if: env.GIT_DIFF
