// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: heimdallv2/topup/query.proto

package topup

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_IsTopupTxOld_FullMethodName                = "/heimdallv2.topup.Query/IsTopupTxOld"
	Query_GetTopupTxSequence_FullMethodName          = "/heimdallv2.topup.Query/GetTopupTxSequence"
	Query_GetDividendAccountByAddress_FullMethodName = "/heimdallv2.topup.Query/GetDividendAccountByAddress"
	Query_GetDividendAccountRootHash_FullMethodName  = "/heimdallv2.topup.Query/GetDividendAccountRootHash"
	Query_VerifyAccountProofByAddress_FullMethodName = "/heimdallv2.topup.Query/VerifyAccountProofByAddress"
	Query_GetAccountProofByAddress_FullMethodName    = "/heimdallv2.topup.Query/GetAccountProofByAddress"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// IsTopupTxOld checks if a topup transaction has already been processed.
	IsTopupTxOld(ctx context.Context, in *QueryTopupSequenceRequest, opts ...grpc.CallOption) (*QueryIsTopupTxOldResponse, error)
	// GetTopupTxSequence returns the sequence number for a topup transaction.
	GetTopupTxSequence(ctx context.Context, in *QueryTopupSequenceRequest, opts ...grpc.CallOption) (*QueryTopupSequenceResponse, error)
	// GetDividendAccountByAddress queries a dividend account by address.
	GetDividendAccountByAddress(ctx context.Context, in *QueryDividendAccountRequest, opts ...grpc.CallOption) (*QueryDividendAccountResponse, error)
	// GetDividendAccountRootHash calculates the Merkle root of all dividend
	// accounts.
	GetDividendAccountRootHash(ctx context.Context, in *QueryDividendAccountRootHashRequest, opts ...grpc.CallOption) (*QueryDividendAccountRootHashResponse, error)
	// VerifyAccountProofByAddress verifies an account proof for a given address.
	VerifyAccountProofByAddress(ctx context.Context, in *QueryVerifyAccountProofRequest, opts ...grpc.CallOption) (*QueryVerifyAccountProofResponse, error)
	// GetAccountProofByAddress retrieves the account proof for a given address.
	GetAccountProofByAddress(ctx context.Context, in *QueryAccountProofRequest, opts ...grpc.CallOption) (*QueryAccountProofResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) IsTopupTxOld(ctx context.Context, in *QueryTopupSequenceRequest, opts ...grpc.CallOption) (*QueryIsTopupTxOldResponse, error) {
	out := new(QueryIsTopupTxOldResponse)
	err := c.cc.Invoke(ctx, Query_IsTopupTxOld_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetTopupTxSequence(ctx context.Context, in *QueryTopupSequenceRequest, opts ...grpc.CallOption) (*QueryTopupSequenceResponse, error) {
	out := new(QueryTopupSequenceResponse)
	err := c.cc.Invoke(ctx, Query_GetTopupTxSequence_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetDividendAccountByAddress(ctx context.Context, in *QueryDividendAccountRequest, opts ...grpc.CallOption) (*QueryDividendAccountResponse, error) {
	out := new(QueryDividendAccountResponse)
	err := c.cc.Invoke(ctx, Query_GetDividendAccountByAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetDividendAccountRootHash(ctx context.Context, in *QueryDividendAccountRootHashRequest, opts ...grpc.CallOption) (*QueryDividendAccountRootHashResponse, error) {
	out := new(QueryDividendAccountRootHashResponse)
	err := c.cc.Invoke(ctx, Query_GetDividendAccountRootHash_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VerifyAccountProofByAddress(ctx context.Context, in *QueryVerifyAccountProofRequest, opts ...grpc.CallOption) (*QueryVerifyAccountProofResponse, error) {
	out := new(QueryVerifyAccountProofResponse)
	err := c.cc.Invoke(ctx, Query_VerifyAccountProofByAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAccountProofByAddress(ctx context.Context, in *QueryAccountProofRequest, opts ...grpc.CallOption) (*QueryAccountProofResponse, error) {
	out := new(QueryAccountProofResponse)
	err := c.cc.Invoke(ctx, Query_GetAccountProofByAddress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// IsTopupTxOld checks if a topup transaction has already been processed.
	IsTopupTxOld(context.Context, *QueryTopupSequenceRequest) (*QueryIsTopupTxOldResponse, error)
	// GetTopupTxSequence returns the sequence number for a topup transaction.
	GetTopupTxSequence(context.Context, *QueryTopupSequenceRequest) (*QueryTopupSequenceResponse, error)
	// GetDividendAccountByAddress queries a dividend account by address.
	GetDividendAccountByAddress(context.Context, *QueryDividendAccountRequest) (*QueryDividendAccountResponse, error)
	// GetDividendAccountRootHash calculates the Merkle root of all dividend
	// accounts.
	GetDividendAccountRootHash(context.Context, *QueryDividendAccountRootHashRequest) (*QueryDividendAccountRootHashResponse, error)
	// VerifyAccountProofByAddress verifies an account proof for a given address.
	VerifyAccountProofByAddress(context.Context, *QueryVerifyAccountProofRequest) (*QueryVerifyAccountProofResponse, error)
	// GetAccountProofByAddress retrieves the account proof for a given address.
	GetAccountProofByAddress(context.Context, *QueryAccountProofRequest) (*QueryAccountProofResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) IsTopupTxOld(context.Context, *QueryTopupSequenceRequest) (*QueryIsTopupTxOldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsTopupTxOld not implemented")
}
func (UnimplementedQueryServer) GetTopupTxSequence(context.Context, *QueryTopupSequenceRequest) (*QueryTopupSequenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopupTxSequence not implemented")
}
func (UnimplementedQueryServer) GetDividendAccountByAddress(context.Context, *QueryDividendAccountRequest) (*QueryDividendAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDividendAccountByAddress not implemented")
}
func (UnimplementedQueryServer) GetDividendAccountRootHash(context.Context, *QueryDividendAccountRootHashRequest) (*QueryDividendAccountRootHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDividendAccountRootHash not implemented")
}
func (UnimplementedQueryServer) VerifyAccountProofByAddress(context.Context, *QueryVerifyAccountProofRequest) (*QueryVerifyAccountProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyAccountProofByAddress not implemented")
}
func (UnimplementedQueryServer) GetAccountProofByAddress(context.Context, *QueryAccountProofRequest) (*QueryAccountProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountProofByAddress not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_IsTopupTxOld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTopupSequenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).IsTopupTxOld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_IsTopupTxOld_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).IsTopupTxOld(ctx, req.(*QueryTopupSequenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetTopupTxSequence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTopupSequenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetTopupTxSequence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetTopupTxSequence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetTopupTxSequence(ctx, req.(*QueryTopupSequenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetDividendAccountByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDividendAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetDividendAccountByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetDividendAccountByAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetDividendAccountByAddress(ctx, req.(*QueryDividendAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetDividendAccountRootHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDividendAccountRootHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetDividendAccountRootHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetDividendAccountRootHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetDividendAccountRootHash(ctx, req.(*QueryDividendAccountRootHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VerifyAccountProofByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVerifyAccountProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VerifyAccountProofByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_VerifyAccountProofByAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VerifyAccountProofByAddress(ctx, req.(*QueryVerifyAccountProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAccountProofByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAccountProofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAccountProofByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetAccountProofByAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAccountProofByAddress(ctx, req.(*QueryAccountProofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "heimdallv2.topup.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsTopupTxOld",
			Handler:    _Query_IsTopupTxOld_Handler,
		},
		{
			MethodName: "GetTopupTxSequence",
			Handler:    _Query_GetTopupTxSequence_Handler,
		},
		{
			MethodName: "GetDividendAccountByAddress",
			Handler:    _Query_GetDividendAccountByAddress_Handler,
		},
		{
			MethodName: "GetDividendAccountRootHash",
			Handler:    _Query_GetDividendAccountRootHash_Handler,
		},
		{
			MethodName: "VerifyAccountProofByAddress",
			Handler:    _Query_VerifyAccountProofByAddress_Handler,
		},
		{
			MethodName: "GetAccountProofByAddress",
			Handler:    _Query_GetAccountProofByAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "heimdallv2/topup/query.proto",
}
