// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: giltconsensusv2/pricefeed/query.proto

package pricefeed

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Query_Params_FullMethodName       = "/giltconsensusv2.pricefeed.Query/Params"
	Query_LatestPrice_FullMethodName  = "/giltconsensusv2.pricefeed.Query/LatestPrice"
	Query_PriceByEpoch_FullMethodName = "/giltconsensusv2.pricefeed.Query/PriceByEpoch"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query defines the gRPC query service for the pricefeed module.
type QueryClient interface {
	// Params queries the pricefeed module parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// LatestPrice queries the latest accepted GILT/GOLD price snapshot.
	LatestPrice(ctx context.Context, in *QueryLatestPriceRequest, opts ...grpc.CallOption) (*QueryLatestPriceResponse, error)
	// PriceByEpoch queries an accepted GILT/GOLD price snapshot by epoch.
	PriceByEpoch(ctx context.Context, in *QueryPriceByEpochRequest, opts ...grpc.CallOption) (*QueryPriceByEpochResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LatestPrice(ctx context.Context, in *QueryLatestPriceRequest, opts ...grpc.CallOption) (*QueryLatestPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryLatestPriceResponse)
	err := c.cc.Invoke(ctx, Query_LatestPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PriceByEpoch(ctx context.Context, in *QueryPriceByEpochRequest, opts ...grpc.CallOption) (*QueryPriceByEpochResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryPriceByEpochResponse)
	err := c.cc.Invoke(ctx, Query_PriceByEpoch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility.
//
// Query defines the gRPC query service for the pricefeed module.
type QueryServer interface {
	// Params queries the pricefeed module parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// LatestPrice queries the latest accepted GILT/GOLD price snapshot.
	LatestPrice(context.Context, *QueryLatestPriceRequest) (*QueryLatestPriceResponse, error)
	// PriceByEpoch queries an accepted GILT/GOLD price snapshot by epoch.
	PriceByEpoch(context.Context, *QueryPriceByEpochRequest) (*QueryPriceByEpochResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) LatestPrice(context.Context, *QueryLatestPriceRequest) (*QueryLatestPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LatestPrice not implemented")
}
func (UnimplementedQueryServer) PriceByEpoch(context.Context, *QueryPriceByEpochRequest) (*QueryPriceByEpochResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PriceByEpoch not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}
func (UnimplementedQueryServer) testEmbeddedByValue()               {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call pancis, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LatestPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLatestPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LatestPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_LatestPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LatestPrice(ctx, req.(*QueryLatestPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PriceByEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPriceByEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PriceByEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_PriceByEpoch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PriceByEpoch(ctx, req.(*QueryPriceByEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "giltconsensusv2.pricefeed.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "LatestPrice",
			Handler:    _Query_LatestPrice_Handler,
		},
		{
			MethodName: "PriceByEpoch",
			Handler:    _Query_PriceByEpoch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "giltconsensusv2/pricefeed/query.proto",
}
