// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: heimdallv2/stake/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryCurrentValidatorSetRequest is the request type for the
// GetCurrentValidatorSet query.
type QueryCurrentValidatorSetRequest struct {
}

func (m *QueryCurrentValidatorSetRequest) Reset()         { *m = QueryCurrentValidatorSetRequest{} }
func (m *QueryCurrentValidatorSetRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCurrentValidatorSetRequest) ProtoMessage()    {}
func (*QueryCurrentValidatorSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64a607450adf12fe, []int{0}
}
func (m *QueryCurrentValidatorSetRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCurrentValidatorSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCurrentValidatorSetRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCurrentValidatorSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCurrentValidatorSetRequest.Merge(m, src)
}
func (m *QueryCurrentValidatorSetRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCurrentValidatorSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCurrentValidatorSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCurrentValidatorSetRequest proto.InternalMessageInfo

// QueryCurrentValidatorSetResponse is the response type for the
// GetCurrentValidatorSet query.
type QueryCurrentValidatorSetResponse struct {
	// The current active validator set.
	ValidatorSet ValidatorSet `protobuf:"bytes,1,opt,name=validator_set,json=validatorSet,proto3" json:"validator_set"`
}

func (m *QueryCurrentValidatorSetResponse) Reset()         { *m = QueryCurrentValidatorSetResponse{} }
func (m *QueryCurrentValidatorSetResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCurrentValidatorSetResponse) ProtoMessage()    {}
func (*QueryCurrentValidatorSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64a607450adf12fe, []int{1}
}
func (m *QueryCurrentValidatorSetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCurrentValidatorSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCurrentValidatorSetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCurrentValidatorSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCurrentValidatorSetResponse.Merge(m, src)
}
func (m *QueryCurrentValidatorSetResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCurrentValidatorSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCurrentValidatorSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCurrentValidatorSetResponse proto.InternalMessageInfo

func (m *QueryCurrentValidatorSetResponse) GetValidatorSet() ValidatorSet {
	if m != nil {
		return m.ValidatorSet
	}
	return ValidatorSet{}
}

// QuerySignerRequest is the request type for the GetSignerByAddress query.
type QuerySignerRequest struct {
	// Signer address to query for.
	ValAddress string `protobuf:"bytes,1,opt,name=val_address,json=valAddress,proto3" json:"val_address,omitempty"`
}

func (m *QuerySignerRequest) Reset()         { *m = QuerySignerRequest{} }
func (m *QuerySignerRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySignerRequest) ProtoMessage()    {}
func (*QuerySignerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64a607450adf12fe, []int{2}
}
func (m *QuerySignerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySignerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySignerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySignerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySignerRequest.Merge(m, src)
}
func (m *QuerySignerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySignerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySignerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySignerRequest proto.InternalMessageInfo

func (m *QuerySignerRequest) GetValAddress() string {
	if m != nil {
		return m.ValAddress
	}
	return ""
}

// QuerySignerResponse is the response type for the GetSignerByAddress query.
type QuerySignerResponse struct {
	// Validator information for the requested signer.
	Validator Validator `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator"`
}

func (m *QuerySignerResponse) Reset()         { *m = QuerySignerResponse{} }
func (m *QuerySignerResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySignerResponse) ProtoMessage()    {}
func (*QuerySignerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64a607450adf12fe, []int{3}
}
func (m *QuerySignerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySignerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySignerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySignerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySignerResponse.Merge(m, src)
}
func (m *QuerySignerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySignerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySignerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySignerResponse proto.InternalMessageInfo

func (m *QuerySignerResponse) GetValidator() Validator {
	if m != nil {
		return m.Validator
	}
	return Validator{}
}

// QueryValidatorRequest is the request type for the GetValidatorById query.
type QueryValidatorRequest struct {
	// Validator ID to query for.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryValidatorRequest) Reset()         { *m = QueryValidatorRequest{} }
func (m *QueryValidatorRequest) String() string { return proto.CompactTextString(m) }
func (*QueryValidatorRequest) ProtoMessage()    {}
func (*QueryValidatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64a607450adf12fe, []int{4}
}
func (m *QueryValidatorRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidatorRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidatorRequest.Merge(m, src)
}
func (m *QueryValidatorRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidatorRequest proto.InternalMessageInfo

func (m *QueryValidatorRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// QueryValidatorResponse is the response type for the GetValidatorById query.
type QueryValidatorResponse struct {
	// Validator information for the requested ID.
	Validator Validator `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator"`
}

func (m *QueryValidatorResponse) Reset()         { *m = QueryValidatorResponse{} }
func (m *QueryValidatorResponse) String() string { return proto.CompactTextString(m) }
func (*QueryValidatorResponse) ProtoMessage()    {}
func (*QueryValidatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64a607450adf12fe, []int{5}
}
func (m *QueryValidatorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidatorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidatorResponse.Merge(m, src)
}
func (m *QueryValidatorResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidatorResponse proto.InternalMessageInfo

func (m *QueryValidatorResponse) GetValidator() Validator {
	if m != nil {
		return m.Validator
	}
	return Validator{}
}

// QueryTotalPowerRequest is the request type for the GetTotalPower query.
type QueryTotalPowerRequest struct {
}

func (m *QueryTotalPowerRequest) Reset()         { *m = QueryTotalPowerRequest{} }
func (m *QueryTotalPowerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTotalPowerRequest) ProtoMessage()    {}
func (*QueryTotalPowerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64a607450adf12fe, []int{6}
}
func (m *QueryTotalPowerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTotalPowerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTotalPowerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTotalPowerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTotalPowerRequest.Merge(m, src)
}
func (m *QueryTotalPowerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTotalPowerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTotalPowerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTotalPowerRequest proto.InternalMessageInfo

// QueryTotalPowerResponse is the response type for the GetTotalPower query.
type QueryTotalPowerResponse struct {
	// Total voting power across all active validators.
	TotalPower int64 `protobuf:"varint,1,opt,name=total_power,json=totalPower,proto3" json:"total_power,omitempty"`
}

func (m *QueryTotalPowerResponse) Reset()         { *m = QueryTotalPowerResponse{} }
func (m *QueryTotalPowerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTotalPowerResponse) ProtoMessage()    {}
func (*QueryTotalPowerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64a607450adf12fe, []int{7}
}
func (m *QueryTotalPowerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTotalPowerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTotalPowerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTotalPowerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTotalPowerResponse.Merge(m, src)
}
func (m *QueryTotalPowerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTotalPowerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTotalPowerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTotalPowerResponse proto.InternalMessageInfo

func (m *QueryTotalPowerResponse) GetTotalPower() int64 {
	if m != nil {
		return m.TotalPower
	}
	return 0
}

// QueryValidatorStatusRequest is the request type for the
// GetValidatorStatusByAddress query.
type QueryValidatorStatusRequest struct {
	// Validator address to check status for.
	ValAddress string `protobuf:"bytes,1,opt,name=val_address,json=valAddress,proto3" json:"val_address,omitempty"`
}

func (m *QueryValidatorStatusRequest) Reset()         { *m = QueryValidatorStatusRequest{} }
func (m *QueryValidatorStatusRequest) String() string { return proto.CompactTextString(m) }
func (*QueryValidatorStatusRequest) ProtoMessage()    {}
func (*QueryValidatorStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64a607450adf12fe, []int{8}
}
func (m *QueryValidatorStatusRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidatorStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidatorStatusRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidatorStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidatorStatusRequest.Merge(m, src)
}
func (m *QueryValidatorStatusRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidatorStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidatorStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidatorStatusRequest proto.InternalMessageInfo

func (m *QueryValidatorStatusRequest) GetValAddress() string {
	if m != nil {
		return m.ValAddress
	}
	return ""
}

// QueryValidatorStatusResponse is the response type for the
// GetValidatorStatusByAddress query.
type QueryValidatorStatusResponse struct {
	// True if the validator is no longer active (exited or not yet joined).
	IsOld bool `protobuf:"varint,1,opt,name=is_old,json=isOld,proto3" json:"is_old,omitempty"`
}

func (m *QueryValidatorStatusResponse) Reset()         { *m = QueryValidatorStatusResponse{} }
func (m *QueryValidatorStatusResponse) String() string { return proto.CompactTextString(m) }
func (*QueryValidatorStatusResponse) ProtoMessage()    {}
func (*QueryValidatorStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64a607450adf12fe, []int{9}
}
func (m *QueryValidatorStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidatorStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidatorStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidatorStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidatorStatusResponse.Merge(m, src)
}
func (m *QueryValidatorStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidatorStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidatorStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidatorStatusResponse proto.InternalMessageInfo

func (m *QueryValidatorStatusResponse) GetIsOld() bool {
	if m != nil {
		return m.IsOld
	}
	return false
}

// QueryStakeIsOldTxRequest is the request type for the IsStakeTxOld query.
type QueryStakeIsOldTxRequest struct {
	// Transaction hash on the root chain.
	TxHash string `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	// Log index within the transaction.
	LogIndex uint64 `protobuf:"varint,2,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
}

func (m *QueryStakeIsOldTxRequest) Reset()         { *m = QueryStakeIsOldTxRequest{} }
func (m *QueryStakeIsOldTxRequest) String() string { return proto.CompactTextString(m) }
func (*QueryStakeIsOldTxRequest) ProtoMessage()    {}
func (*QueryStakeIsOldTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64a607450adf12fe, []int{10}
}
func (m *QueryStakeIsOldTxRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStakeIsOldTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStakeIsOldTxRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStakeIsOldTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStakeIsOldTxRequest.Merge(m, src)
}
func (m *QueryStakeIsOldTxRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryStakeIsOldTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStakeIsOldTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStakeIsOldTxRequest proto.InternalMessageInfo

func (m *QueryStakeIsOldTxRequest) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *QueryStakeIsOldTxRequest) GetLogIndex() uint64 {
	if m != nil {
		return m.LogIndex
	}
	return 0
}

// QueryStakeIsOldTxResponse is the response type for the IsStakeTxOld query.
type QueryStakeIsOldTxResponse struct {
	// True if this stake transaction has already been processed.
	IsOld bool `protobuf:"varint,1,opt,name=is_old,json=isOld,proto3" json:"is_old,omitempty"`
}

func (m *QueryStakeIsOldTxResponse) Reset()         { *m = QueryStakeIsOldTxResponse{} }
func (m *QueryStakeIsOldTxResponse) String() string { return proto.CompactTextString(m) }
func (*QueryStakeIsOldTxResponse) ProtoMessage()    {}
func (*QueryStakeIsOldTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64a607450adf12fe, []int{11}
}
func (m *QueryStakeIsOldTxResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryStakeIsOldTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryStakeIsOldTxResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryStakeIsOldTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryStakeIsOldTxResponse.Merge(m, src)
}
func (m *QueryStakeIsOldTxResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryStakeIsOldTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryStakeIsOldTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryStakeIsOldTxResponse proto.InternalMessageInfo

func (m *QueryStakeIsOldTxResponse) GetIsOld() bool {
	if m != nil {
		return m.IsOld
	}
	return false
}

// QueryProposersRequest is the request type for the GetProposersByTimes query.
type QueryProposersRequest struct {
	// Number of future proposers to return in the rotation sequence.
	Times uint64 `protobuf:"varint,1,opt,name=times,proto3" json:"times,omitempty"`
}

func (m *QueryProposersRequest) Reset()         { *m = QueryProposersRequest{} }
func (m *QueryProposersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryProposersRequest) ProtoMessage()    {}
func (*QueryProposersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64a607450adf12fe, []int{12}
}
func (m *QueryProposersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryProposersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryProposersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryProposersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProposersRequest.Merge(m, src)
}
func (m *QueryProposersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryProposersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProposersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProposersRequest proto.InternalMessageInfo

func (m *QueryProposersRequest) GetTimes() uint64 {
	if m != nil {
		return m.Times
	}
	return 0
}

// QueryProposersResponse is the response type for the GetProposersByTimes
// query.
type QueryProposersResponse struct {
	// List of validators in proposer rotation order.
	Proposers []Validator `protobuf:"bytes,1,rep,name=proposers,proto3" json:"proposers"`
}

func (m *QueryProposersResponse) Reset()         { *m = QueryProposersResponse{} }
func (m *QueryProposersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryProposersResponse) ProtoMessage()    {}
func (*QueryProposersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64a607450adf12fe, []int{13}
}
func (m *QueryProposersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryProposersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryProposersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryProposersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProposersResponse.Merge(m, src)
}
func (m *QueryProposersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryProposersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProposersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProposersResponse proto.InternalMessageInfo

func (m *QueryProposersResponse) GetProposers() []Validator {
	if m != nil {
		return m.Proposers
	}
	return nil
}

// QueryCurrentProposerRequest is the request type for the GetCurrentProposer
// query.
type QueryCurrentProposerRequest struct {
}

func (m *QueryCurrentProposerRequest) Reset()         { *m = QueryCurrentProposerRequest{} }
func (m *QueryCurrentProposerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCurrentProposerRequest) ProtoMessage()    {}
func (*QueryCurrentProposerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_64a607450adf12fe, []int{14}
}
func (m *QueryCurrentProposerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCurrentProposerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCurrentProposerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCurrentProposerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCurrentProposerRequest.Merge(m, src)
}
func (m *QueryCurrentProposerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCurrentProposerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCurrentProposerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCurrentProposerRequest proto.InternalMessageInfo

// QueryCurrentProposerResponse is the response type for the GetCurrentProposer
// query.
type QueryCurrentProposerResponse struct {
	// The validator currently designated as proposer.
	Validator Validator `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator"`
}

func (m *QueryCurrentProposerResponse) Reset()         { *m = QueryCurrentProposerResponse{} }
func (m *QueryCurrentProposerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCurrentProposerResponse) ProtoMessage()    {}
func (*QueryCurrentProposerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_64a607450adf12fe, []int{15}
}
func (m *QueryCurrentProposerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCurrentProposerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCurrentProposerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCurrentProposerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCurrentProposerResponse.Merge(m, src)
}
func (m *QueryCurrentProposerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCurrentProposerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCurrentProposerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCurrentProposerResponse proto.InternalMessageInfo

func (m *QueryCurrentProposerResponse) GetValidator() Validator {
	if m != nil {
		return m.Validator
	}
	return Validator{}
}

func init() {
	proto.RegisterType((*QueryCurrentValidatorSetRequest)(nil), "heimdallv2.stake.QueryCurrentValidatorSetRequest")
	proto.RegisterType((*QueryCurrentValidatorSetResponse)(nil), "heimdallv2.stake.QueryCurrentValidatorSetResponse")
	proto.RegisterType((*QuerySignerRequest)(nil), "heimdallv2.stake.QuerySignerRequest")
	proto.RegisterType((*QuerySignerResponse)(nil), "heimdallv2.stake.QuerySignerResponse")
	proto.RegisterType((*QueryValidatorRequest)(nil), "heimdallv2.stake.QueryValidatorRequest")
	proto.RegisterType((*QueryValidatorResponse)(nil), "heimdallv2.stake.QueryValidatorResponse")
	proto.RegisterType((*QueryTotalPowerRequest)(nil), "heimdallv2.stake.QueryTotalPowerRequest")
	proto.RegisterType((*QueryTotalPowerResponse)(nil), "heimdallv2.stake.QueryTotalPowerResponse")
	proto.RegisterType((*QueryValidatorStatusRequest)(nil), "heimdallv2.stake.QueryValidatorStatusRequest")
	proto.RegisterType((*QueryValidatorStatusResponse)(nil), "heimdallv2.stake.QueryValidatorStatusResponse")
	proto.RegisterType((*QueryStakeIsOldTxRequest)(nil), "heimdallv2.stake.QueryStakeIsOldTxRequest")
	proto.RegisterType((*QueryStakeIsOldTxResponse)(nil), "heimdallv2.stake.QueryStakeIsOldTxResponse")
	proto.RegisterType((*QueryProposersRequest)(nil), "heimdallv2.stake.QueryProposersRequest")
	proto.RegisterType((*QueryProposersResponse)(nil), "heimdallv2.stake.QueryProposersResponse")
	proto.RegisterType((*QueryCurrentProposerRequest)(nil), "heimdallv2.stake.QueryCurrentProposerRequest")
	proto.RegisterType((*QueryCurrentProposerResponse)(nil), "heimdallv2.stake.QueryCurrentProposerResponse")
}

func init() { proto.RegisterFile("heimdallv2/stake/query.proto", fileDescriptor_64a607450adf12fe) }

var fileDescriptor_64a607450adf12fe = []byte{
	// 874 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0x4d, 0x6f, 0xe3, 0x44,
	0x18, 0xc7, 0xe3, 0x94, 0x94, 0x66, 0xda, 0x4a, 0x65, 0xfa, 0x16, 0x9c, 0xd4, 0x0d, 0x16, 0x7d,
	0xa1, 0x28, 0x36, 0x0d, 0x5c, 0x90, 0x7a, 0x69, 0x00, 0xa5, 0xb9, 0xd0, 0xd2, 0x46, 0x1c, 0x40,
	0x22, 0x72, 0xeb, 0x91, 0x63, 0xe1, 0x78, 0x52, 0xcf, 0x24, 0x38, 0xaa, 0x7a, 0x00, 0x09, 0x09,
	0xc4, 0x01, 0x24, 0x6e, 0x5c, 0xb9, 0x70, 0xec, 0x85, 0xef, 0xd0, 0x63, 0xa5, 0xbd, 0xec, 0x69,
	0xb5, 0x6a, 0x57, 0xda, 0xaf, 0xb1, 0xf2, 0x78, 0xfc, 0x12, 0x27, 0xde, 0xa4, 0x52, 0x2f, 0x55,
	0xf4, 0xbc, 0xfe, 0xfc, 0x3c, 0xcf, 0xfc, 0x55, 0x50, 0x6a, 0x23, 0xb3, 0xa3, 0x6b, 0x96, 0xd5,
	0xaf, 0xaa, 0x84, 0x6a, 0x3f, 0x22, 0xf5, 0xb2, 0x87, 0x9c, 0x81, 0xd2, 0x75, 0x30, 0xc5, 0x70,
	0x29, 0xf2, 0x2a, 0xcc, 0x2b, 0xbe, 0xa7, 0x75, 0x4c, 0x1b, 0xab, 0xec, 0xaf, 0x1f, 0x24, 0x16,
	0x2f, 0x30, 0xe9, 0x60, 0xe2, 0x27, 0xaa, 0xfd, 0xfd, 0x78, 0x05, 0x71, 0xc5, 0xc0, 0x06, 0x66,
	0x3f, 0x55, 0xef, 0x17, 0xb7, 0x96, 0x0c, 0x8c, 0x0d, 0x0b, 0xa9, 0x5a, 0xd7, 0x54, 0x35, 0xdb,
	0xc6, 0x54, 0xa3, 0x26, 0xb6, 0x09, 0xf7, 0x96, 0x47, 0x98, 0xfa, 0x9a, 0x65, 0xea, 0x1a, 0xc5,
	0x8e, 0x1f, 0x21, 0x7f, 0x00, 0x36, 0xbf, 0xf1, 0x9a, 0x7c, 0xd1, 0x73, 0x1c, 0x64, 0xd3, 0x6f,
	0x03, 0xf7, 0x19, 0xa2, 0xa7, 0xe8, 0xb2, 0x87, 0x08, 0x95, 0x1d, 0x50, 0x4e, 0x0f, 0x21, 0x5d,
	0x6c, 0x13, 0x04, 0xbf, 0x06, 0x8b, 0x61, 0xe5, 0x16, 0x41, 0xb4, 0x20, 0x94, 0x85, 0xdd, 0xf9,
	0xaa, 0xa4, 0x24, 0x3f, 0x5b, 0x89, 0xa7, 0xd7, 0xf2, 0xb7, 0x2f, 0x36, 0x33, 0xff, 0xbd, 0xbe,
	0xd9, 0x13, 0x4e, 0x17, 0xfa, 0x31, 0x87, 0x7c, 0x00, 0x20, 0xeb, 0x79, 0x66, 0x1a, 0x36, 0x72,
	0x38, 0x09, 0xdc, 0x06, 0xf3, 0x7d, 0xcd, 0x6a, 0x69, 0xba, 0xee, 0x20, 0x42, 0x58, 0x8f, 0x7c,
	0x2d, 0xe7, 0xe7, 0x83, 0xbe, 0x66, 0x1d, 0xfa, 0x0e, 0xf9, 0x7b, 0xb0, 0x3c, 0x94, 0xcd, 0x21,
	0xbf, 0x04, 0xf9, 0xb0, 0x09, 0x07, 0x2c, 0xbe, 0x05, 0x30, 0x4e, 0x17, 0x25, 0xca, 0x0a, 0x58,
	0x65, 0xc5, 0xc3, 0xb8, 0x80, 0x6e, 0x15, 0x64, 0x4d, 0x9d, 0xd5, 0x7d, 0x27, 0x80, 0xca, 0x9a,
	0xba, 0xfc, 0x03, 0x58, 0x4b, 0xc6, 0x3f, 0x29, 0x4f, 0x81, 0xd7, 0x6f, 0x62, 0xaa, 0x59, 0x27,
	0xf8, 0xa7, 0x70, 0x5c, 0xf2, 0x21, 0x58, 0x1f, 0xf1, 0xf0, 0xd6, 0xdb, 0x60, 0x9e, 0x7a, 0xd6,
	0x56, 0xd7, 0x33, 0xb3, 0xe6, 0x33, 0xe1, 0x24, 0x69, 0x18, 0x2f, 0x7f, 0x05, 0x8a, 0xc3, 0xf0,
	0x67, 0x54, 0xa3, 0x3d, 0xf2, 0xd8, 0x85, 0x1c, 0x80, 0xd2, 0xf8, 0x32, 0x1c, 0xa7, 0x04, 0x66,
	0x4d, 0xd2, 0xc2, 0x96, 0x3f, 0xbe, 0xb9, 0xa0, 0x44, 0xce, 0x24, 0xc7, 0x96, 0x37, 0xc1, 0x82,
	0xbf, 0x4e, 0x6f, 0x1e, 0x0d, 0xcf, 0xd4, 0x74, 0x03, 0x02, 0x09, 0xbc, 0x4b, 0xdd, 0x56, 0x5b,
	0x23, 0xed, 0xe1, 0xee, 0xb3, 0xd4, 0x3d, 0xd2, 0x48, 0x1b, 0xca, 0x20, 0x6f, 0x61, 0xa3, 0x65,
	0xda, 0x3a, 0x72, 0x0b, 0xd9, 0xf8, 0x6e, 0xe6, 0x2c, 0x6c, 0x34, 0x3c, 0xb3, 0xfc, 0x39, 0x78,
	0x7f, 0x4c, 0xfd, 0xa9, 0xd0, 0x3e, 0xe3, 0xc7, 0x70, 0xe2, 0xe0, 0x2e, 0x26, 0xc8, 0x09, 0x27,
	0x53, 0x04, 0x39, 0x6a, 0x76, 0x10, 0x19, 0xbe, 0x07, 0xdf, 0x16, 0x9e, 0x44, 0x2c, 0x2b, 0x3a,
	0x89, 0x6e, 0x60, 0x2c, 0x08, 0xe5, 0x99, 0xc7, 0x9c, 0x44, 0x98, 0x28, 0x6f, 0xf0, 0xad, 0xf1,
	0x17, 0x1b, 0xb4, 0x09, 0xee, 0x42, 0xe7, 0xdb, 0x18, 0x71, 0x3f, 0xe5, 0x5d, 0x56, 0xff, 0xcf,
	0x83, 0x1c, 0x6b, 0x03, 0xff, 0x15, 0xc0, 0x5a, 0x1d, 0xd1, 0x31, 0xfa, 0x01, 0xf7, 0x47, 0xeb,
	0x4e, 0x90, 0x23, 0xb1, 0xfa, 0x98, 0x14, 0xff, 0x8b, 0x64, 0xf9, 0x37, 0x8f, 0xee, 0x97, 0x67,
	0xaf, 0xfe, 0xce, 0xae, 0xc3, 0xd5, 0xa4, 0x14, 0x92, 0x0a, 0x41, 0x14, 0xfe, 0x21, 0x00, 0x58,
	0x47, 0xd4, 0xd7, 0x8c, 0xda, 0x80, 0x9f, 0x2e, 0xfc, 0x30, 0xa5, 0xdd, 0x90, 0x32, 0x89, 0x5b,
	0x13, 0xa2, 0x38, 0xc7, 0x6e, 0xc4, 0xb1, 0x01, 0x8b, 0x9c, 0x83, 0xb0, 0x18, 0xf5, 0x2a, 0xf6,
	0x92, 0xae, 0xe1, 0xef, 0x02, 0x58, 0xaa, 0xa3, 0xe8, 0x6b, 0x6a, 0x83, 0x86, 0x0e, 0x77, 0x52,
	0xba, 0x24, 0xa5, 0x48, 0xdc, 0x9d, 0x1c, 0x38, 0xd5, 0x64, 0xd4, 0x2b, 0x53, 0xbf, 0x86, 0x37,
	0x02, 0x28, 0xc6, 0x59, 0xfc, 0xc7, 0x1b, 0x8d, 0xa8, 0x32, 0xa9, 0xdb, 0x90, 0x68, 0x88, 0xca,
	0xb4, 0xe1, 0x1c, 0xb1, 0x1a, 0x21, 0xee, 0xc0, 0xad, 0x24, 0x62, 0x85, 0xb0, 0xe8, 0xc4, 0xf8,
	0x7e, 0x15, 0xc0, 0x62, 0x1d, 0xd1, 0x48, 0xf9, 0x60, 0xda, 0x48, 0x46, 0x64, 0x53, 0xfc, 0x68,
	0x8a, 0x48, 0x8e, 0xb6, 0x19, 0xa1, 0xad, 0x40, 0xc8, 0xd1, 0x98, 0x7c, 0x56, 0x98, 0xb0, 0xc2,
	0x9f, 0x05, 0xb0, 0xd0, 0x20, 0x4c, 0x58, 0x9a, 0xee, 0xb1, 0xa5, 0xc3, 0xbd, 0xb4, 0x43, 0x19,
	0xd5, 0x36, 0xf1, 0xe3, 0xa9, 0x62, 0x39, 0x4a, 0x81, 0x51, 0x40, 0xb8, 0xc4, 0x29, 0x4c, 0x52,
	0xc1, 0x96, 0x5e, 0xa1, 0x2e, 0xfc, 0xc7, 0x3f, 0xec, 0xc4, 0x6b, 0x4f, 0xdd, 0xda, 0x78, 0xd1,
	0x48, 0xdd, 0x5a, 0x8a, 0x88, 0xc8, 0x5b, 0xd1, 0x68, 0x44, 0x58, 0xe0, 0x50, 0xa1, 0x44, 0xa9,
	0x17, 0x7e, 0x1a, 0xfc, 0x53, 0x00, 0xcb, 0x75, 0x14, 0xa6, 0x93, 0xda, 0xa0, 0xe9, 0x49, 0x64,
	0xea, 0xa9, 0x27, 0x85, 0x36, 0xf5, 0xd4, 0x47, 0xb4, 0x75, 0x12, 0xd1, 0x15, 0xd3, 0xe6, 0xeb,
	0xda, 0xd1, 0xed, 0xbd, 0x24, 0xdc, 0xdd, 0x4b, 0xc2, 0xcb, 0x7b, 0x49, 0xf8, 0xeb, 0x41, 0xca,
	0xdc, 0x3d, 0x48, 0x99, 0xe7, 0x0f, 0x52, 0xe6, 0x3b, 0xc5, 0x30, 0x69, 0xbb, 0x77, 0xae, 0x5c,
	0xe0, 0x8e, 0xfa, 0x89, 0x7b, 0x82, 0xad, 0x81, 0x81, 0x6d, 0x35, 0x68, 0x5f, 0xe9, 0x57, 0x55,
	0x37, 0x38, 0x81, 0x41, 0x17, 0x91, 0xf3, 0x59, 0xf6, 0x2f, 0xd6, 0xa7, 0x6f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x44, 0xf5, 0x43, 0x61, 0x1a, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// GetCurrentValidatorSet queries the current active validator set.
	GetCurrentValidatorSet(ctx context.Context, in *QueryCurrentValidatorSetRequest, opts ...grpc.CallOption) (*QueryCurrentValidatorSetResponse, error)
	// GetSignerByAddress queries validator information by signer address.
	GetSignerByAddress(ctx context.Context, in *QuerySignerRequest, opts ...grpc.CallOption) (*QuerySignerResponse, error)
	// GetValidatorById queries validator information by validator ID.
	GetValidatorById(ctx context.Context, in *QueryValidatorRequest, opts ...grpc.CallOption) (*QueryValidatorResponse, error)
	// GetValidatorStatusByAddress queries whether a validator is active or old.
	GetValidatorStatusByAddress(ctx context.Context, in *QueryValidatorStatusRequest, opts ...grpc.CallOption) (*QueryValidatorStatusResponse, error)
	// GetTotalPower queries the sum of all validators' voting power.
	GetTotalPower(ctx context.Context, in *QueryTotalPowerRequest, opts ...grpc.CallOption) (*QueryTotalPowerResponse, error)
	// IsStakeTxOld checks if a stake transaction has already been processed.
	IsStakeTxOld(ctx context.Context, in *QueryStakeIsOldTxRequest, opts ...grpc.CallOption) (*QueryStakeIsOldTxResponse, error)
	// GetCurrentProposer queries the validator currently designated as proposer.
	GetCurrentProposer(ctx context.Context, in *QueryCurrentProposerRequest, opts ...grpc.CallOption) (*QueryCurrentProposerResponse, error)
	// GetProposersByTimes returns the next N proposers in the rotation sequence.
	GetProposersByTimes(ctx context.Context, in *QueryProposersRequest, opts ...grpc.CallOption) (*QueryProposersResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetCurrentValidatorSet(ctx context.Context, in *QueryCurrentValidatorSetRequest, opts ...grpc.CallOption) (*QueryCurrentValidatorSetResponse, error) {
	out := new(QueryCurrentValidatorSetResponse)
	err := c.cc.Invoke(ctx, "/heimdallv2.stake.Query/GetCurrentValidatorSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetSignerByAddress(ctx context.Context, in *QuerySignerRequest, opts ...grpc.CallOption) (*QuerySignerResponse, error) {
	out := new(QuerySignerResponse)
	err := c.cc.Invoke(ctx, "/heimdallv2.stake.Query/GetSignerByAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetValidatorById(ctx context.Context, in *QueryValidatorRequest, opts ...grpc.CallOption) (*QueryValidatorResponse, error) {
	out := new(QueryValidatorResponse)
	err := c.cc.Invoke(ctx, "/heimdallv2.stake.Query/GetValidatorById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetValidatorStatusByAddress(ctx context.Context, in *QueryValidatorStatusRequest, opts ...grpc.CallOption) (*QueryValidatorStatusResponse, error) {
	out := new(QueryValidatorStatusResponse)
	err := c.cc.Invoke(ctx, "/heimdallv2.stake.Query/GetValidatorStatusByAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetTotalPower(ctx context.Context, in *QueryTotalPowerRequest, opts ...grpc.CallOption) (*QueryTotalPowerResponse, error) {
	out := new(QueryTotalPowerResponse)
	err := c.cc.Invoke(ctx, "/heimdallv2.stake.Query/GetTotalPower", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) IsStakeTxOld(ctx context.Context, in *QueryStakeIsOldTxRequest, opts ...grpc.CallOption) (*QueryStakeIsOldTxResponse, error) {
	out := new(QueryStakeIsOldTxResponse)
	err := c.cc.Invoke(ctx, "/heimdallv2.stake.Query/IsStakeTxOld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetCurrentProposer(ctx context.Context, in *QueryCurrentProposerRequest, opts ...grpc.CallOption) (*QueryCurrentProposerResponse, error) {
	out := new(QueryCurrentProposerResponse)
	err := c.cc.Invoke(ctx, "/heimdallv2.stake.Query/GetCurrentProposer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetProposersByTimes(ctx context.Context, in *QueryProposersRequest, opts ...grpc.CallOption) (*QueryProposersResponse, error) {
	out := new(QueryProposersResponse)
	err := c.cc.Invoke(ctx, "/heimdallv2.stake.Query/GetProposersByTimes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// GetCurrentValidatorSet queries the current active validator set.
	GetCurrentValidatorSet(context.Context, *QueryCurrentValidatorSetRequest) (*QueryCurrentValidatorSetResponse, error)
	// GetSignerByAddress queries validator information by signer address.
	GetSignerByAddress(context.Context, *QuerySignerRequest) (*QuerySignerResponse, error)
	// GetValidatorById queries validator information by validator ID.
	GetValidatorById(context.Context, *QueryValidatorRequest) (*QueryValidatorResponse, error)
	// GetValidatorStatusByAddress queries whether a validator is active or old.
	GetValidatorStatusByAddress(context.Context, *QueryValidatorStatusRequest) (*QueryValidatorStatusResponse, error)
	// GetTotalPower queries the sum of all validators' voting power.
	GetTotalPower(context.Context, *QueryTotalPowerRequest) (*QueryTotalPowerResponse, error)
	// IsStakeTxOld checks if a stake transaction has already been processed.
	IsStakeTxOld(context.Context, *QueryStakeIsOldTxRequest) (*QueryStakeIsOldTxResponse, error)
	// GetCurrentProposer queries the validator currently designated as proposer.
	GetCurrentProposer(context.Context, *QueryCurrentProposerRequest) (*QueryCurrentProposerResponse, error)
	// GetProposersByTimes returns the next N proposers in the rotation sequence.
	GetProposersByTimes(context.Context, *QueryProposersRequest) (*QueryProposersResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GetCurrentValidatorSet(ctx context.Context, req *QueryCurrentValidatorSetRequest) (*QueryCurrentValidatorSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentValidatorSet not implemented")
}
func (*UnimplementedQueryServer) GetSignerByAddress(ctx context.Context, req *QuerySignerRequest) (*QuerySignerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSignerByAddress not implemented")
}
func (*UnimplementedQueryServer) GetValidatorById(ctx context.Context, req *QueryValidatorRequest) (*QueryValidatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValidatorById not implemented")
}
func (*UnimplementedQueryServer) GetValidatorStatusByAddress(ctx context.Context, req *QueryValidatorStatusRequest) (*QueryValidatorStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValidatorStatusByAddress not implemented")
}
func (*UnimplementedQueryServer) GetTotalPower(ctx context.Context, req *QueryTotalPowerRequest) (*QueryTotalPowerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTotalPower not implemented")
}
func (*UnimplementedQueryServer) IsStakeTxOld(ctx context.Context, req *QueryStakeIsOldTxRequest) (*QueryStakeIsOldTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsStakeTxOld not implemented")
}
func (*UnimplementedQueryServer) GetCurrentProposer(ctx context.Context, req *QueryCurrentProposerRequest) (*QueryCurrentProposerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentProposer not implemented")
}
func (*UnimplementedQueryServer) GetProposersByTimes(ctx context.Context, req *QueryProposersRequest) (*QueryProposersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProposersByTimes not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GetCurrentValidatorSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCurrentValidatorSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetCurrentValidatorSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/heimdallv2.stake.Query/GetCurrentValidatorSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetCurrentValidatorSet(ctx, req.(*QueryCurrentValidatorSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetSignerByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySignerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetSignerByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/heimdallv2.stake.Query/GetSignerByAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetSignerByAddress(ctx, req.(*QuerySignerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetValidatorById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryValidatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetValidatorById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/heimdallv2.stake.Query/GetValidatorById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetValidatorById(ctx, req.(*QueryValidatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetValidatorStatusByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryValidatorStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetValidatorStatusByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/heimdallv2.stake.Query/GetValidatorStatusByAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetValidatorStatusByAddress(ctx, req.(*QueryValidatorStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetTotalPower_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTotalPowerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetTotalPower(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/heimdallv2.stake.Query/GetTotalPower",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetTotalPower(ctx, req.(*QueryTotalPowerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_IsStakeTxOld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryStakeIsOldTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).IsStakeTxOld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/heimdallv2.stake.Query/IsStakeTxOld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).IsStakeTxOld(ctx, req.(*QueryStakeIsOldTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetCurrentProposer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCurrentProposerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetCurrentProposer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/heimdallv2.stake.Query/GetCurrentProposer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetCurrentProposer(ctx, req.(*QueryCurrentProposerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetProposersByTimes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryProposersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetProposersByTimes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/heimdallv2.stake.Query/GetProposersByTimes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetProposersByTimes(ctx, req.(*QueryProposersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "heimdallv2.stake.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentValidatorSet",
			Handler:    _Query_GetCurrentValidatorSet_Handler,
		},
		{
			MethodName: "GetSignerByAddress",
			Handler:    _Query_GetSignerByAddress_Handler,
		},
		{
			MethodName: "GetValidatorById",
			Handler:    _Query_GetValidatorById_Handler,
		},
		{
			MethodName: "GetValidatorStatusByAddress",
			Handler:    _Query_GetValidatorStatusByAddress_Handler,
		},
		{
			MethodName: "GetTotalPower",
			Handler:    _Query_GetTotalPower_Handler,
		},
		{
			MethodName: "IsStakeTxOld",
			Handler:    _Query_IsStakeTxOld_Handler,
		},
		{
			MethodName: "GetCurrentProposer",
			Handler:    _Query_GetCurrentProposer_Handler,
		},
		{
			MethodName: "GetProposersByTimes",
			Handler:    _Query_GetProposersByTimes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "heimdallv2/stake/query.proto",
}

func (m *QueryCurrentValidatorSetRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCurrentValidatorSetRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCurrentValidatorSetRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryCurrentValidatorSetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCurrentValidatorSetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCurrentValidatorSetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ValidatorSet.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QuerySignerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySignerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySignerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValAddress) > 0 {
		i -= len(m.ValAddress)
		copy(dAtA[i:], m.ValAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ValAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QuerySignerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySignerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySignerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Validator.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryValidatorRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidatorRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidatorRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryValidatorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidatorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidatorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Validator.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryTotalPowerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTotalPowerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTotalPowerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryTotalPowerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTotalPowerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTotalPowerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TotalPower != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TotalPower))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryValidatorStatusRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidatorStatusRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidatorStatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValAddress) > 0 {
		i -= len(m.ValAddress)
		copy(dAtA[i:], m.ValAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ValAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryValidatorStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidatorStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidatorStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsOld {
		i--
		if m.IsOld {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryStakeIsOldTxRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStakeIsOldTxRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStakeIsOldTxRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LogIndex != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.LogIndex))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TxHash) > 0 {
		i -= len(m.TxHash)
		copy(dAtA[i:], m.TxHash)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TxHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryStakeIsOldTxResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryStakeIsOldTxResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryStakeIsOldTxResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsOld {
		i--
		if m.IsOld {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryProposersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryProposersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryProposersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Times != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Times))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryProposersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryProposersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryProposersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Proposers) > 0 {
		for iNdEx := len(m.Proposers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Proposers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryCurrentProposerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCurrentProposerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCurrentProposerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryCurrentProposerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCurrentProposerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCurrentProposerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Validator.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryCurrentValidatorSetRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryCurrentValidatorSetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ValidatorSet.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QuerySignerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QuerySignerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Validator.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryValidatorRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryValidatorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Validator.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryTotalPowerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryTotalPowerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TotalPower != 0 {
		n += 1 + sovQuery(uint64(m.TotalPower))
	}
	return n
}

func (m *QueryValidatorStatusRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryValidatorStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IsOld {
		n += 2
	}
	return n
}

func (m *QueryStakeIsOldTxRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.LogIndex != 0 {
		n += 1 + sovQuery(uint64(m.LogIndex))
	}
	return n
}

func (m *QueryStakeIsOldTxResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IsOld {
		n += 2
	}
	return n
}

func (m *QueryProposersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Times != 0 {
		n += 1 + sovQuery(uint64(m.Times))
	}
	return n
}

func (m *QueryProposersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Proposers) > 0 {
		for _, e := range m.Proposers {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryCurrentProposerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryCurrentProposerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Validator.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryCurrentValidatorSetRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCurrentValidatorSetRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCurrentValidatorSetRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCurrentValidatorSetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCurrentValidatorSetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCurrentValidatorSetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorSet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ValidatorSet.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySignerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySignerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySignerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySignerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySignerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySignerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Validator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryValidatorRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidatorRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidatorRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryValidatorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidatorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidatorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Validator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTotalPowerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTotalPowerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTotalPowerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTotalPowerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTotalPowerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTotalPowerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalPower", wireType)
			}
			m.TotalPower = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalPower |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryValidatorStatusRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidatorStatusRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidatorStatusRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryValidatorStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidatorStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidatorStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsOld", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsOld = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStakeIsOldTxRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStakeIsOldTxRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStakeIsOldTxRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LogIndex", wireType)
			}
			m.LogIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LogIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryStakeIsOldTxResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryStakeIsOldTxResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryStakeIsOldTxResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsOld", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsOld = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryProposersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryProposersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryProposersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Times", wireType)
			}
			m.Times = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Times |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryProposersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryProposersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryProposersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proposers = append(m.Proposers, Validator{})
			if err := m.Proposers[len(m.Proposers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCurrentProposerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCurrentProposerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCurrentProposerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCurrentProposerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCurrentProposerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCurrentProposerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Validator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
