name: mainnet_deb_profiles

on:
  push:
    paths:
      - '**'
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'

jobs:
  build:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      # Variables
      - name: Adding TAG to ENV
        run: echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
      - name: adding version
        run: |
          NUMERIC_VERSION=$( echo ${{ env.GIT_TAG }} | sed 's/[^0-9.]//g' ) 
          echo "VERSION=$NUMERIC_VERSION" >> $GITHUB_ENV

      - name: Making directory structure for yaml
        run: mkdir -p packaging/deb/giltconsensusd/var/lib/giltconsensus/config
      - name: making directory structure for the systemd
        run: mkdir -p packaging/deb/giltconsensusd/lib/systemd/system
      - name: delete old control file
        run: rm -rf packaging/deb/giltconsensusd/DEBIAN/control

      # Control file creation
      - name: create control file
        run: |
          touch packaging/deb/giltconsensusd/DEBIAN/control
          echo "Package: giltconsensus-profile" >> packaging/deb/giltconsensusd/DEBIAN/control
          echo "Version: ${{ env.VERSION }}" >> packaging/deb/giltconsensusd/DEBIAN/control
          echo "Section: base" >> packaging/deb/giltconsensusd/DEBIAN/control
          echo "Priority: optional" >> packaging/deb/giltconsensusd/DEBIAN/control
          echo "Architecture: all" >> packaging/deb/giltconsensusd/DEBIAN/control
          echo "Maintainer: devops@gilt.technology" >> packaging/deb/giltconsensusd/DEBIAN/control
          echo "Description: giltconsensus profile package" >> packaging/deb/giltconsensusd/DEBIAN/control

      #### Sentry Profiles ####
      - name: Setting up ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/deb/giltconsensusd packaging/deb/giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: all
          NODE: sentry
          NETWORK: mainnet
      - name: Copying the postinst for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/postinst.profile.mainnet packaging/deb/giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/postinst
        env:
          ARCH: all
          NODE: sentry
          NETWORK: mainnet
      - name: Copying preinst for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/preinst.${{ env.NETWORK }} packaging/deb/giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/preinst
        env:
          ARCH: all
          NODE: sentry
          NETWORK: mainnet
      - name: Copying config for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/config/${{ env.NETWORK }}/app.toml packaging/deb/giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/var/lib/giltconsensus/config/app.toml
        env:
          ARCH: all
          NODE: sentry
          NETWORK: mainnet
      - name: Copying config for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/config/${{ env.NETWORK }}/config.toml packaging/deb/giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/var/lib/giltconsensus/config/config.toml
        env:
          ARCH: all
          NODE: sentry
          NETWORK: mainnet
      - name: Copying config for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/config/${{ env.NETWORK }}/client.toml packaging/deb/giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/var/lib/giltconsensus/config/client.toml
        env:
          ARCH: all
          NODE: sentry
          NETWORK: mainnet
      - name: Copying the prerm for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/prerm packaging/deb/giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/prerm
        env:
          ARCH: all
          NODE: sentry
          NETWORK: mainnet
      - name: Copying the postrm for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/postrm.profile packaging/deb/giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/postrm
        env:
          ARCH: all
          NODE: sentry
          NETWORK: mainnet
      - name: Copying systemd file for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/systemd/giltconsensusd-mainnet-sentry.service packaging/deb/giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/lib/systemd/system/giltconsensusd.service
        env:
          ARCH: all
          NODE: sentry
          NETWORK: mainnet
      - name: Building ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }} profile
        run: dpkg-deb --build --root-owner-group packaging/deb/giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: all
          NODE: sentry
          NETWORK: mainnet

      ### Validator Profiles ###
      - name: Prepping giltconsensus ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/deb/giltconsensusd packaging/deb/giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: all
          NODE: validator
          NETWORK: mainnet
      - name: Copying Postinstall script for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/postinst.profile.mainnet packaging/deb/giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/postinst
        env:
          ARCH: all
          NODE: validator
          NETWORK: mainnet
      - name: Copying the prerm for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/prerm packaging/deb/giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/prerm
        env:
          ARCH: all
          NODE: validator
          NETWORK: mainnet
      - name: Copying preinst for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/preinst.${{ env.NETWORK }} packaging/deb/giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/preinst
        env:
          ARCH: all
          NODE: validator
          NETWORK: mainnet
      - name: Copying config for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/config/${{ env.NETWORK }}/app.toml packaging/deb/giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/var/lib/giltconsensus/config/app.toml
        env:
          ARCH: all
          NODE: validator
          NETWORK: mainnet
      - name: Copying config for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/config/${{ env.NETWORK }}/config.toml packaging/deb/giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/var/lib/giltconsensus/config/config.toml
        env:
          ARCH: all
          NODE: validator
          NETWORK: mainnet
      - name: Copying config for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/config/${{ env.NETWORK }}/client.toml packaging/deb/giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/var/lib/giltconsensus/config/client.toml
        env:
          ARCH: all
          NODE: validator
          NETWORK: mainnet
      - name: Copying the postrm for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/package_scripts/postrm.profile packaging/deb/giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/DEBIAN/postrm
        env:
          ARCH: all
          NODE: validator
          NETWORK: mainnet
      - name: Copying systemd file for ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }}
        run: cp -rp packaging/templates/systemd/giltconsensusd-mainnet-validator.service packaging/deb/giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}/lib/systemd/system/giltconsensusd.service
        env:
          ARCH: all
          NODE: validator
          NETWORK: mainnet
      - name: Building giltconsensus ${{ env.NODE }} on ${{ env.NETWORK }} on ${{ env.ARCH }} profile
        run: dpkg-deb --build --root-owner-group packaging/deb/giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}
        env:
          ARCH: all
          NODE: validator
          NETWORK: mainnet

      # Shasum
      - name: shasum the giltconsensus debian profile package
        run: cd packaging/deb/ && sha256sum giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}.deb > giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}.deb.checksum
        env:
          ARCH: all
          NODE: validator
          NETWORK: mainnet

      - name: shasum the giltconsensus debian profile package
        run: cd packaging/deb/ && sha256sum giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}.deb > giltconsensus-${{ env.NETWORK }}-${{ env.NODE }}-config_${{ env.GIT_TAG }}-${{ env.ARCH }}.deb.checksum
        env:
          ARCH: all
          NODE: sentry
          NETWORK: mainnet

      ############ Check and Upload ##########################
      - name: Confirming package built
        run: ls -ltr packaging/deb/ | grep giltconsensus

      - name: Release giltconsensus Packages
        uses: softprops/action-gh-release@v2.2.2
        with:
          tag_name: ${{ env.GIT_TAG }}
          make_latest: false
          files: |
            packaging/deb/giltconsensus-mainnet-**.deb
            packaging/deb/giltconsensus-mainnet-**.deb.checksum
