export enum ViewState {
  WALLET_INFO,
  SEND_ASSETS,
  SEND_FORM,
  CONFIRM_TRANSACTION,
  // TODO: add confirm copy link
  // CONFIRM_COPY_LINK,
  CLAIM_GIFT,
  CLAIM_GIFT_CONFIRM,
  GIFT_INFO_DETAIL,
  CONNECTED_WALLETS,
  RECEIVE_OPTIONS,
  RECEIVE_QR,
}

export enum SEND_ENTRY {
  CREATE_GIFT,
  SEND_ONLY,
}
