# This is an example docker-compose file for starting up gilt-consensus required components.
# To run standalone without Gilt for development and testing purposes.
# Do not use this for production.
services:
  rabbitmq:
    container_name: rabbitmq
    image: mirror.gcr.io/library/rabbitmq:3-alpine
    ports:
      - "5672:5672" # RabbitMQ
    restart: unless-stopped

  giltconsd:
    container_name: giltconsd
    image: giltchain/gilt-consensus:latest
    build: .
    restart: unless-stopped
    environment:
      - GILTCONSENSUS_ETH_RPC_URL=https://sepolia.infura.io/v3/[YOUR_INFURA_PROJECT_ID]
      - GILTCONSENSUS_AMQP_URL=amqp://guest:guest@rabbitmq:5672
    volumes:
      - ./data:/giltconsensus
    ports:
      - "26656:26656" # P2P (TCP)
      - "26657:26657" # RPC (TCP)
      - "1317:1317"   # GiltConsensus REST API
    depends_on:
      - rabbitmq
    command:
      - start
      - --p2p.laddr=tcp://0.0.0.0:26656
      - --rpc.laddr=tcp://0.0.0.0:26657
      - --rest-server
      - --bridge
      - --all
